// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="nn_fpga_top_nn_fpga_top,hls_ip_2025_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a35t-cpg236-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.279000,HLS_SYN_LAT=54510,HLS_SYN_TPT=none,HLS_SYN_MEM=45,HLS_SYN_DSP=0,HLS_SYN_FF=6616,HLS_SYN_LUT=8039,HLS_VERSION=2025_1}" *)

module nn_fpga_top (
        ap_clk,
        ap_rst,
        image_idx,
        led_out
);

parameter    ap_ST_fsm_state1 = 14'd1;
parameter    ap_ST_fsm_state2 = 14'd2;
parameter    ap_ST_fsm_state3 = 14'd4;
parameter    ap_ST_fsm_state4 = 14'd8;
parameter    ap_ST_fsm_state5 = 14'd16;
parameter    ap_ST_fsm_state6 = 14'd32;
parameter    ap_ST_fsm_state7 = 14'd64;
parameter    ap_ST_fsm_state8 = 14'd128;
parameter    ap_ST_fsm_state9 = 14'd256;
parameter    ap_ST_fsm_state10 = 14'd512;
parameter    ap_ST_fsm_state11 = 14'd1024;
parameter    ap_ST_fsm_state12 = 14'd2048;
parameter    ap_ST_fsm_state13 = 14'd4096;
parameter    ap_ST_fsm_state14 = 14'd8192;

input   ap_clk;
input   ap_rst;
input  [3:0] image_idx;
output  [3:0] led_out;

wire   [5:0] B1_address0;
wire   [4:0] B1_q0;
wire   [12:0] mul_ln63_fu_207_p2;
reg   [12:0] mul_ln63_reg_304;
(* fsm_encoding = "none" *) reg   [13:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [15:0] phi_mul_load_reg_309;
wire    ap_CS_fsm_state4;
reg   [6:0] i_reg_314;
wire   [63:0] zext_ln29_fu_257_p1;
reg   [63:0] zext_ln29_reg_322;
wire    ap_CS_fsm_state5;
reg   [4:0] B1_load_reg_332;
wire    ap_CS_fsm_state6;
wire   [15:0] acc_fu_267_p2;
reg   [15:0] acc_reg_337;
wire    ap_CS_fsm_state7;
wire    ap_CS_fsm_state10;
reg   [15:0] max_val_reg_347;
wire    ap_CS_fsm_state11;
reg   [3:0] output_address0;
reg    output_ce0;
reg    output_we0;
wire   [15:0] output_q0;
reg   [9:0] image_address0;
reg    image_ce0;
reg    image_we0;
wire   [9:0] image_q0;
reg   [5:0] h1_address0;
reg    h1_ce0;
wire   [15:0] h1_q0;
wire    grp_nn_fpga_top_Pipeline_VITIS_LOOP_63_1_fu_157_ap_start;
wire    grp_nn_fpga_top_Pipeline_VITIS_LOOP_63_1_fu_157_ap_done;
wire    grp_nn_fpga_top_Pipeline_VITIS_LOOP_63_1_fu_157_ap_idle;
wire    grp_nn_fpga_top_Pipeline_VITIS_LOOP_63_1_fu_157_ap_ready;
wire   [9:0] grp_nn_fpga_top_Pipeline_VITIS_LOOP_63_1_fu_157_image_r_address0;
wire    grp_nn_fpga_top_Pipeline_VITIS_LOOP_63_1_fu_157_image_r_ce0;
wire    grp_nn_fpga_top_Pipeline_VITIS_LOOP_63_1_fu_157_image_r_we0;
wire   [9:0] grp_nn_fpga_top_Pipeline_VITIS_LOOP_63_1_fu_157_image_r_d0;
wire    grp_nn_fpga_top_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_47_2_fu_165_ap_start;
wire    grp_nn_fpga_top_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_47_2_fu_165_ap_done;
wire    grp_nn_fpga_top_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_47_2_fu_165_ap_idle;
wire    grp_nn_fpga_top_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_47_2_fu_165_ap_ready;
wire   [5:0] grp_nn_fpga_top_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_47_2_fu_165_h1_address0;
wire    grp_nn_fpga_top_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_47_2_fu_165_h1_ce0;
wire   [3:0] grp_nn_fpga_top_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_47_2_fu_165_output_r_address0;
wire    grp_nn_fpga_top_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_47_2_fu_165_output_r_ce0;
wire    grp_nn_fpga_top_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_47_2_fu_165_output_r_we0;
wire   [15:0] grp_nn_fpga_top_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_47_2_fu_165_output_r_d0;
wire    grp_nn_fpga_top_Pipeline_VITIS_LOOP_32_2_fu_175_ap_start;
wire    grp_nn_fpga_top_Pipeline_VITIS_LOOP_32_2_fu_175_ap_done;
wire    grp_nn_fpga_top_Pipeline_VITIS_LOOP_32_2_fu_175_ap_idle;
wire    grp_nn_fpga_top_Pipeline_VITIS_LOOP_32_2_fu_175_ap_ready;
wire   [9:0] grp_nn_fpga_top_Pipeline_VITIS_LOOP_32_2_fu_175_image_r_address0;
wire    grp_nn_fpga_top_Pipeline_VITIS_LOOP_32_2_fu_175_image_r_ce0;
wire   [15:0] grp_nn_fpga_top_Pipeline_VITIS_LOOP_32_2_fu_175_acc_1_out;
wire    grp_nn_fpga_top_Pipeline_VITIS_LOOP_32_2_fu_175_acc_1_out_ap_vld;
wire    grp_my_tanh_fu_184_ap_start;
wire    grp_my_tanh_fu_184_ap_done;
wire    grp_my_tanh_fu_184_ap_idle;
wire    grp_my_tanh_fu_184_ap_ready;
wire   [15:0] grp_my_tanh_fu_184_ap_return;
wire    grp_nn_fpga_top_Pipeline_VITIS_LOOP_77_2_fu_196_ap_start;
wire    grp_nn_fpga_top_Pipeline_VITIS_LOOP_77_2_fu_196_ap_done;
wire    grp_nn_fpga_top_Pipeline_VITIS_LOOP_77_2_fu_196_ap_idle;
wire    grp_nn_fpga_top_Pipeline_VITIS_LOOP_77_2_fu_196_ap_ready;
wire   [3:0] grp_nn_fpga_top_Pipeline_VITIS_LOOP_77_2_fu_196_output_r_address0;
wire    grp_nn_fpga_top_Pipeline_VITIS_LOOP_77_2_fu_196_output_r_ce0;
wire   [3:0] grp_nn_fpga_top_Pipeline_VITIS_LOOP_77_2_fu_196_max_idx_out;
wire    grp_nn_fpga_top_Pipeline_VITIS_LOOP_77_2_fu_196_max_idx_out_ap_vld;
reg    grp_nn_fpga_top_Pipeline_VITIS_LOOP_63_1_fu_157_ap_start_reg;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
reg    grp_nn_fpga_top_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_47_2_fu_165_ap_start_reg;
wire   [0:0] icmp_ln29_fu_235_p2;
wire    ap_CS_fsm_state9;
reg    grp_nn_fpga_top_Pipeline_VITIS_LOOP_32_2_fu_175_ap_start_reg;
reg    grp_my_tanh_fu_184_ap_start_reg;
wire    ap_CS_fsm_state8;
reg    grp_nn_fpga_top_Pipeline_VITIS_LOOP_77_2_fu_196_ap_start_reg;
wire    ap_CS_fsm_state12;
wire    ap_CS_fsm_state13;
reg   [3:0] max_idx_loc_fu_86;
reg   [15:0] phi_mul_fu_78;
wire   [15:0] add_ln29_1_fu_229_p2;
reg   [6:0] i_1_fu_82;
wire   [6:0] add_ln29_fu_241_p2;
wire    ap_CS_fsm_state14;
reg    B1_ce0_local;
reg    h1_we0_local;
reg    h1_ce0_local;
reg    output_ce0_local;
wire   [3:0] mul_ln63_fu_207_p0;
wire   [10:0] mul_ln63_fu_207_p1;
wire  signed [15:0] sext_ln36_fu_264_p1;
reg   [13:0] ap_NS_fsm;
wire    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
reg    ap_ST_fsm_state8_blk;
reg    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
reg    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire   [12:0] mul_ln63_fu_207_p00;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 14'd1;
#0 grp_nn_fpga_top_Pipeline_VITIS_LOOP_63_1_fu_157_ap_start_reg = 1'b0;
#0 grp_nn_fpga_top_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_47_2_fu_165_ap_start_reg = 1'b0;
#0 grp_nn_fpga_top_Pipeline_VITIS_LOOP_32_2_fu_175_ap_start_reg = 1'b0;
#0 grp_my_tanh_fu_184_ap_start_reg = 1'b0;
#0 grp_nn_fpga_top_Pipeline_VITIS_LOOP_77_2_fu_196_ap_start_reg = 1'b0;
#0 phi_mul_fu_78 = 16'd0;
#0 i_1_fu_82 = 7'd0;
end

nn_fpga_top_B1_ROM_AUTO_1R #(
    .DataWidth( 5 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
B1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(B1_address0),
    .ce0(B1_ce0_local),
    .q0(B1_q0)
);

nn_fpga_top_output_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 10 ),
    .AddressWidth( 4 ))
output_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(output_address0),
    .ce0(output_ce0),
    .we0(output_we0),
    .d0(grp_nn_fpga_top_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_47_2_fu_165_output_r_d0),
    .q0(output_q0)
);

nn_fpga_top_image_RAM_AUTO_1R1W #(
    .DataWidth( 10 ),
    .AddressRange( 784 ),
    .AddressWidth( 10 ))
image_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(image_address0),
    .ce0(image_ce0),
    .we0(image_we0),
    .d0(grp_nn_fpga_top_Pipeline_VITIS_LOOP_63_1_fu_157_image_r_d0),
    .q0(image_q0)
);

nn_fpga_top_h1_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
h1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(h1_address0),
    .ce0(h1_ce0),
    .we0(h1_we0_local),
    .d0(grp_my_tanh_fu_184_ap_return),
    .q0(h1_q0)
);

nn_fpga_top_nn_fpga_top_Pipeline_VITIS_LOOP_63_1 grp_nn_fpga_top_Pipeline_VITIS_LOOP_63_1_fu_157(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_nn_fpga_top_Pipeline_VITIS_LOOP_63_1_fu_157_ap_start),
    .ap_done(grp_nn_fpga_top_Pipeline_VITIS_LOOP_63_1_fu_157_ap_done),
    .ap_idle(grp_nn_fpga_top_Pipeline_VITIS_LOOP_63_1_fu_157_ap_idle),
    .ap_ready(grp_nn_fpga_top_Pipeline_VITIS_LOOP_63_1_fu_157_ap_ready),
    .mul_ln65(mul_ln63_reg_304),
    .image_r_address0(grp_nn_fpga_top_Pipeline_VITIS_LOOP_63_1_fu_157_image_r_address0),
    .image_r_ce0(grp_nn_fpga_top_Pipeline_VITIS_LOOP_63_1_fu_157_image_r_ce0),
    .image_r_we0(grp_nn_fpga_top_Pipeline_VITIS_LOOP_63_1_fu_157_image_r_we0),
    .image_r_d0(grp_nn_fpga_top_Pipeline_VITIS_LOOP_63_1_fu_157_image_r_d0)
);

nn_fpga_top_nn_fpga_top_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_47_2 grp_nn_fpga_top_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_47_2_fu_165(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_nn_fpga_top_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_47_2_fu_165_ap_start),
    .ap_done(grp_nn_fpga_top_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_47_2_fu_165_ap_done),
    .ap_idle(grp_nn_fpga_top_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_47_2_fu_165_ap_idle),
    .ap_ready(grp_nn_fpga_top_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_47_2_fu_165_ap_ready),
    .h1_address0(grp_nn_fpga_top_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_47_2_fu_165_h1_address0),
    .h1_ce0(grp_nn_fpga_top_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_47_2_fu_165_h1_ce0),
    .h1_q0(h1_q0),
    .output_r_address0(grp_nn_fpga_top_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_47_2_fu_165_output_r_address0),
    .output_r_ce0(grp_nn_fpga_top_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_47_2_fu_165_output_r_ce0),
    .output_r_we0(grp_nn_fpga_top_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_47_2_fu_165_output_r_we0),
    .output_r_d0(grp_nn_fpga_top_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_47_2_fu_165_output_r_d0)
);

nn_fpga_top_nn_fpga_top_Pipeline_VITIS_LOOP_32_2 grp_nn_fpga_top_Pipeline_VITIS_LOOP_32_2_fu_175(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_nn_fpga_top_Pipeline_VITIS_LOOP_32_2_fu_175_ap_start),
    .ap_done(grp_nn_fpga_top_Pipeline_VITIS_LOOP_32_2_fu_175_ap_done),
    .ap_idle(grp_nn_fpga_top_Pipeline_VITIS_LOOP_32_2_fu_175_ap_idle),
    .ap_ready(grp_nn_fpga_top_Pipeline_VITIS_LOOP_32_2_fu_175_ap_ready),
    .phi_mul(phi_mul_load_reg_309),
    .image_r_address0(grp_nn_fpga_top_Pipeline_VITIS_LOOP_32_2_fu_175_image_r_address0),
    .image_r_ce0(grp_nn_fpga_top_Pipeline_VITIS_LOOP_32_2_fu_175_image_r_ce0),
    .image_r_q0(image_q0),
    .acc_1_out(grp_nn_fpga_top_Pipeline_VITIS_LOOP_32_2_fu_175_acc_1_out),
    .acc_1_out_ap_vld(grp_nn_fpga_top_Pipeline_VITIS_LOOP_32_2_fu_175_acc_1_out_ap_vld)
);

nn_fpga_top_my_tanh grp_my_tanh_fu_184(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_my_tanh_fu_184_ap_start),
    .ap_done(grp_my_tanh_fu_184_ap_done),
    .ap_idle(grp_my_tanh_fu_184_ap_idle),
    .ap_ready(grp_my_tanh_fu_184_ap_ready),
    .x(acc_reg_337),
    .ap_return(grp_my_tanh_fu_184_ap_return)
);

nn_fpga_top_nn_fpga_top_Pipeline_VITIS_LOOP_77_2 grp_nn_fpga_top_Pipeline_VITIS_LOOP_77_2_fu_196(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_nn_fpga_top_Pipeline_VITIS_LOOP_77_2_fu_196_ap_start),
    .ap_done(grp_nn_fpga_top_Pipeline_VITIS_LOOP_77_2_fu_196_ap_done),
    .ap_idle(grp_nn_fpga_top_Pipeline_VITIS_LOOP_77_2_fu_196_ap_idle),
    .ap_ready(grp_nn_fpga_top_Pipeline_VITIS_LOOP_77_2_fu_196_ap_ready),
    .max_val(max_val_reg_347),
    .output_r_address0(grp_nn_fpga_top_Pipeline_VITIS_LOOP_77_2_fu_196_output_r_address0),
    .output_r_ce0(grp_nn_fpga_top_Pipeline_VITIS_LOOP_77_2_fu_196_output_r_ce0),
    .output_r_q0(output_q0),
    .max_idx_out(grp_nn_fpga_top_Pipeline_VITIS_LOOP_77_2_fu_196_max_idx_out),
    .max_idx_out_ap_vld(grp_nn_fpga_top_Pipeline_VITIS_LOOP_77_2_fu_196_max_idx_out_ap_vld)
);

nn_fpga_top_mul_4ns_11ns_13_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 13 ))
mul_4ns_11ns_13_1_1_U56(
    .din0(mul_ln63_fu_207_p0),
    .din1(mul_ln63_fu_207_p1),
    .dout(mul_ln63_fu_207_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_my_tanh_fu_184_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state7)) begin
            grp_my_tanh_fu_184_ap_start_reg <= 1'b1;
        end else if ((grp_my_tanh_fu_184_ap_ready == 1'b1)) begin
            grp_my_tanh_fu_184_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_nn_fpga_top_Pipeline_VITIS_LOOP_32_2_fu_175_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state5)) begin
            grp_nn_fpga_top_Pipeline_VITIS_LOOP_32_2_fu_175_ap_start_reg <= 1'b1;
        end else if ((grp_nn_fpga_top_Pipeline_VITIS_LOOP_32_2_fu_175_ap_ready == 1'b1)) begin
            grp_nn_fpga_top_Pipeline_VITIS_LOOP_32_2_fu_175_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_nn_fpga_top_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_47_2_fu_165_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln29_fu_235_p2 == 1'd1))) begin
            grp_nn_fpga_top_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_47_2_fu_165_ap_start_reg <= 1'b1;
        end else if ((grp_nn_fpga_top_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_47_2_fu_165_ap_ready == 1'b1)) begin
            grp_nn_fpga_top_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_47_2_fu_165_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_nn_fpga_top_Pipeline_VITIS_LOOP_63_1_fu_157_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_nn_fpga_top_Pipeline_VITIS_LOOP_63_1_fu_157_ap_start_reg <= 1'b1;
        end else if ((grp_nn_fpga_top_Pipeline_VITIS_LOOP_63_1_fu_157_ap_ready == 1'b1)) begin
            grp_nn_fpga_top_Pipeline_VITIS_LOOP_63_1_fu_157_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_nn_fpga_top_Pipeline_VITIS_LOOP_77_2_fu_196_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state12)) begin
            grp_nn_fpga_top_Pipeline_VITIS_LOOP_77_2_fu_196_ap_start_reg <= 1'b1;
        end else if ((grp_nn_fpga_top_Pipeline_VITIS_LOOP_77_2_fu_196_ap_ready == 1'b1)) begin
            grp_nn_fpga_top_Pipeline_VITIS_LOOP_77_2_fu_196_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        i_1_fu_82 <= 7'd0;
    end else if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln29_fu_235_p2 == 1'd0))) begin
        i_1_fu_82 <= add_ln29_fu_241_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        phi_mul_fu_78 <= 16'd0;
    end else if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln29_fu_235_p2 == 1'd0))) begin
        phi_mul_fu_78 <= add_ln29_1_fu_229_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        B1_load_reg_332 <= B1_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        acc_reg_337 <= acc_fu_267_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        i_reg_314 <= i_1_fu_82;
        phi_mul_load_reg_309 <= phi_mul_fu_78;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state13) & (grp_nn_fpga_top_Pipeline_VITIS_LOOP_77_2_fu_196_max_idx_out_ap_vld == 1'b1))) begin
        max_idx_loc_fu_86 <= grp_nn_fpga_top_Pipeline_VITIS_LOOP_77_2_fu_196_max_idx_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        max_val_reg_347 <= output_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        mul_ln63_reg_304 <= mul_ln63_fu_207_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        zext_ln29_reg_322[6 : 0] <= zext_ln29_fu_257_p1[6 : 0];
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        B1_ce0_local = 1'b1;
    end else begin
        B1_ce0_local = 1'b0;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

always @ (*) begin
    if ((grp_nn_fpga_top_Pipeline_VITIS_LOOP_77_2_fu_196_ap_done == 1'b0)) begin
        ap_ST_fsm_state13_blk = 1'b1;
    end else begin
        ap_ST_fsm_state13_blk = 1'b0;
    end
end

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state1_blk = 1'b0;

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_nn_fpga_top_Pipeline_VITIS_LOOP_63_1_fu_157_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((grp_nn_fpga_top_Pipeline_VITIS_LOOP_32_2_fu_175_ap_done == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

assign ap_ST_fsm_state7_blk = 1'b0;

always @ (*) begin
    if ((grp_my_tanh_fu_184_ap_done == 1'b0)) begin
        ap_ST_fsm_state8_blk = 1'b1;
    end else begin
        ap_ST_fsm_state8_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_nn_fpga_top_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_47_2_fu_165_ap_done == 1'b0)) begin
        ap_ST_fsm_state9_blk = 1'b1;
    end else begin
        ap_ST_fsm_state9_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        h1_address0 = grp_nn_fpga_top_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_47_2_fu_165_h1_address0;
    end else begin
        h1_address0 = zext_ln29_reg_322;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        h1_ce0 = grp_nn_fpga_top_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_47_2_fu_165_h1_ce0;
    end else begin
        h1_ce0 = h1_ce0_local;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) & (grp_my_tanh_fu_184_ap_done == 1'b1))) begin
        h1_ce0_local = 1'b1;
    end else begin
        h1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) & (grp_my_tanh_fu_184_ap_done == 1'b1))) begin
        h1_we0_local = 1'b1;
    end else begin
        h1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        image_address0 = grp_nn_fpga_top_Pipeline_VITIS_LOOP_32_2_fu_175_image_r_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        image_address0 = grp_nn_fpga_top_Pipeline_VITIS_LOOP_63_1_fu_157_image_r_address0;
    end else begin
        image_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        image_ce0 = grp_nn_fpga_top_Pipeline_VITIS_LOOP_32_2_fu_175_image_r_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        image_ce0 = grp_nn_fpga_top_Pipeline_VITIS_LOOP_63_1_fu_157_image_r_ce0;
    end else begin
        image_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        image_we0 = grp_nn_fpga_top_Pipeline_VITIS_LOOP_63_1_fu_157_image_r_we0;
    end else begin
        image_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        output_address0 = grp_nn_fpga_top_Pipeline_VITIS_LOOP_77_2_fu_196_output_r_address0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        output_address0 = grp_nn_fpga_top_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_47_2_fu_165_output_r_address0;
    end else begin
        output_address0 = 64'd0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        output_ce0 = grp_nn_fpga_top_Pipeline_VITIS_LOOP_77_2_fu_196_output_r_ce0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        output_ce0 = grp_nn_fpga_top_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_47_2_fu_165_output_r_ce0;
    end else begin
        output_ce0 = output_ce0_local;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        output_ce0_local = 1'b1;
    end else begin
        output_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        output_we0 = grp_nn_fpga_top_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_47_2_fu_165_output_r_we0;
    end else begin
        output_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (grp_nn_fpga_top_Pipeline_VITIS_LOOP_63_1_fu_157_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln29_fu_235_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((1'b1 == ap_CS_fsm_state6) & (grp_nn_fpga_top_Pipeline_VITIS_LOOP_32_2_fu_175_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            if (((1'b1 == ap_CS_fsm_state8) & (grp_my_tanh_fu_184_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state9 : begin
            if (((1'b1 == ap_CS_fsm_state9) & (grp_nn_fpga_top_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_47_2_fu_165_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            if (((1'b1 == ap_CS_fsm_state13) & (grp_nn_fpga_top_Pipeline_VITIS_LOOP_77_2_fu_196_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign B1_address0 = zext_ln29_fu_257_p1;

assign acc_fu_267_p2 = ($signed(sext_ln36_fu_264_p1) + $signed(grp_nn_fpga_top_Pipeline_VITIS_LOOP_32_2_fu_175_acc_1_out));

assign add_ln29_1_fu_229_p2 = (phi_mul_fu_78 + 16'd784);

assign add_ln29_fu_241_p2 = (i_1_fu_82 + 7'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign grp_my_tanh_fu_184_ap_start = grp_my_tanh_fu_184_ap_start_reg;

assign grp_nn_fpga_top_Pipeline_VITIS_LOOP_32_2_fu_175_ap_start = grp_nn_fpga_top_Pipeline_VITIS_LOOP_32_2_fu_175_ap_start_reg;

assign grp_nn_fpga_top_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_47_2_fu_165_ap_start = grp_nn_fpga_top_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_47_2_fu_165_ap_start_reg;

assign grp_nn_fpga_top_Pipeline_VITIS_LOOP_63_1_fu_157_ap_start = grp_nn_fpga_top_Pipeline_VITIS_LOOP_63_1_fu_157_ap_start_reg;

assign grp_nn_fpga_top_Pipeline_VITIS_LOOP_77_2_fu_196_ap_start = grp_nn_fpga_top_Pipeline_VITIS_LOOP_77_2_fu_196_ap_start_reg;

assign icmp_ln29_fu_235_p2 = ((i_1_fu_82 == 7'd64) ? 1'b1 : 1'b0);

assign led_out = max_idx_loc_fu_86;

assign mul_ln63_fu_207_p0 = mul_ln63_fu_207_p00;

assign mul_ln63_fu_207_p00 = image_idx;

assign mul_ln63_fu_207_p1 = 13'd784;

assign sext_ln36_fu_264_p1 = $signed(B1_load_reg_332);

assign zext_ln29_fu_257_p1 = i_reg_314;

always @ (posedge ap_clk) begin
    zext_ln29_reg_322[63:7] <= 57'b000000000000000000000000000000000000000000000000000000000;
end

endmodule //nn_fpga_top
