-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity nn_fpga_top is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    image_idx : IN STD_LOGIC_VECTOR (3 downto 0);
    led_out : OUT STD_LOGIC_VECTOR (3 downto 0) );
end;


architecture behav of nn_fpga_top is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "nn_fpga_top_nn_fpga_top,hls_ip_2025_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a35t-cpg236-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.279000,HLS_SYN_LAT=54510,HLS_SYN_TPT=none,HLS_SYN_MEM=45,HLS_SYN_DSP=0,HLS_SYN_FF=6616,HLS_SYN_LUT=8039,HLS_VERSION=2025_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (13 downto 0) := "00000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (13 downto 0) := "00000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (13 downto 0) := "00000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (13 downto 0) := "00000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (13 downto 0) := "00000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (13 downto 0) := "00000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (13 downto 0) := "00001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (13 downto 0) := "00010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (13 downto 0) := "00100000000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (13 downto 0) := "01000000000000";
    constant ap_ST_fsm_state14 : STD_LOGIC_VECTOR (13 downto 0) := "10000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv13_310 : STD_LOGIC_VECTOR (12 downto 0) := "0001100010000";
    constant ap_const_lv16_310 : STD_LOGIC_VECTOR (15 downto 0) := "0000001100010000";
    constant ap_const_lv7_40 : STD_LOGIC_VECTOR (6 downto 0) := "1000000";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";

    signal B1_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal B1_q0 : STD_LOGIC_VECTOR (4 downto 0);
    signal mul_ln63_fu_207_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal mul_ln63_reg_304 : STD_LOGIC_VECTOR (12 downto 0);
    signal ap_CS_fsm : STD_LOGIC_VECTOR (13 downto 0) := "00000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal phi_mul_load_reg_309 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal i_reg_314 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln29_fu_257_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln29_reg_322 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal B1_load_reg_332 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal acc_fu_267_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal acc_reg_337 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal max_val_reg_347 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state11 : signal is "none";
    signal output_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal output_ce0 : STD_LOGIC;
    signal output_we0 : STD_LOGIC;
    signal output_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal image_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal image_ce0 : STD_LOGIC;
    signal image_we0 : STD_LOGIC;
    signal image_q0 : STD_LOGIC_VECTOR (9 downto 0);
    signal h1_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal h1_ce0 : STD_LOGIC;
    signal h1_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_nn_fpga_top_Pipeline_VITIS_LOOP_63_1_fu_157_ap_start : STD_LOGIC;
    signal grp_nn_fpga_top_Pipeline_VITIS_LOOP_63_1_fu_157_ap_done : STD_LOGIC;
    signal grp_nn_fpga_top_Pipeline_VITIS_LOOP_63_1_fu_157_ap_idle : STD_LOGIC;
    signal grp_nn_fpga_top_Pipeline_VITIS_LOOP_63_1_fu_157_ap_ready : STD_LOGIC;
    signal grp_nn_fpga_top_Pipeline_VITIS_LOOP_63_1_fu_157_image_r_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_nn_fpga_top_Pipeline_VITIS_LOOP_63_1_fu_157_image_r_ce0 : STD_LOGIC;
    signal grp_nn_fpga_top_Pipeline_VITIS_LOOP_63_1_fu_157_image_r_we0 : STD_LOGIC;
    signal grp_nn_fpga_top_Pipeline_VITIS_LOOP_63_1_fu_157_image_r_d0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_nn_fpga_top_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_47_2_fu_165_ap_start : STD_LOGIC;
    signal grp_nn_fpga_top_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_47_2_fu_165_ap_done : STD_LOGIC;
    signal grp_nn_fpga_top_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_47_2_fu_165_ap_idle : STD_LOGIC;
    signal grp_nn_fpga_top_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_47_2_fu_165_ap_ready : STD_LOGIC;
    signal grp_nn_fpga_top_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_47_2_fu_165_h1_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_nn_fpga_top_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_47_2_fu_165_h1_ce0 : STD_LOGIC;
    signal grp_nn_fpga_top_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_47_2_fu_165_output_r_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_nn_fpga_top_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_47_2_fu_165_output_r_ce0 : STD_LOGIC;
    signal grp_nn_fpga_top_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_47_2_fu_165_output_r_we0 : STD_LOGIC;
    signal grp_nn_fpga_top_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_47_2_fu_165_output_r_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_nn_fpga_top_Pipeline_VITIS_LOOP_32_2_fu_175_ap_start : STD_LOGIC;
    signal grp_nn_fpga_top_Pipeline_VITIS_LOOP_32_2_fu_175_ap_done : STD_LOGIC;
    signal grp_nn_fpga_top_Pipeline_VITIS_LOOP_32_2_fu_175_ap_idle : STD_LOGIC;
    signal grp_nn_fpga_top_Pipeline_VITIS_LOOP_32_2_fu_175_ap_ready : STD_LOGIC;
    signal grp_nn_fpga_top_Pipeline_VITIS_LOOP_32_2_fu_175_image_r_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_nn_fpga_top_Pipeline_VITIS_LOOP_32_2_fu_175_image_r_ce0 : STD_LOGIC;
    signal grp_nn_fpga_top_Pipeline_VITIS_LOOP_32_2_fu_175_acc_1_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_nn_fpga_top_Pipeline_VITIS_LOOP_32_2_fu_175_acc_1_out_ap_vld : STD_LOGIC;
    signal grp_my_tanh_fu_184_ap_start : STD_LOGIC;
    signal grp_my_tanh_fu_184_ap_done : STD_LOGIC;
    signal grp_my_tanh_fu_184_ap_idle : STD_LOGIC;
    signal grp_my_tanh_fu_184_ap_ready : STD_LOGIC;
    signal grp_my_tanh_fu_184_ap_return : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_nn_fpga_top_Pipeline_VITIS_LOOP_77_2_fu_196_ap_start : STD_LOGIC;
    signal grp_nn_fpga_top_Pipeline_VITIS_LOOP_77_2_fu_196_ap_done : STD_LOGIC;
    signal grp_nn_fpga_top_Pipeline_VITIS_LOOP_77_2_fu_196_ap_idle : STD_LOGIC;
    signal grp_nn_fpga_top_Pipeline_VITIS_LOOP_77_2_fu_196_ap_ready : STD_LOGIC;
    signal grp_nn_fpga_top_Pipeline_VITIS_LOOP_77_2_fu_196_output_r_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_nn_fpga_top_Pipeline_VITIS_LOOP_77_2_fu_196_output_r_ce0 : STD_LOGIC;
    signal grp_nn_fpga_top_Pipeline_VITIS_LOOP_77_2_fu_196_max_idx_out : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_nn_fpga_top_Pipeline_VITIS_LOOP_77_2_fu_196_max_idx_out_ap_vld : STD_LOGIC;
    signal grp_nn_fpga_top_Pipeline_VITIS_LOOP_63_1_fu_157_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal grp_nn_fpga_top_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_47_2_fu_165_ap_start_reg : STD_LOGIC := '0';
    signal icmp_ln29_fu_235_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal grp_nn_fpga_top_Pipeline_VITIS_LOOP_32_2_fu_175_ap_start_reg : STD_LOGIC := '0';
    signal grp_my_tanh_fu_184_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal grp_nn_fpga_top_Pipeline_VITIS_LOOP_77_2_fu_196_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state12 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state12 : signal is "none";
    signal ap_CS_fsm_state13 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state13 : signal is "none";
    signal max_idx_loc_fu_86 : STD_LOGIC_VECTOR (3 downto 0);
    signal phi_mul_fu_78 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal add_ln29_1_fu_229_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal i_1_fu_82 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    signal add_ln29_fu_241_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_CS_fsm_state14 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state14 : signal is "none";
    signal B1_ce0_local : STD_LOGIC;
    signal h1_we0_local : STD_LOGIC;
    signal h1_ce0_local : STD_LOGIC;
    signal output_ce0_local : STD_LOGIC;
    signal mul_ln63_fu_207_p0 : STD_LOGIC_VECTOR (3 downto 0);
    signal mul_ln63_fu_207_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln36_fu_264_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (13 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_ST_fsm_state11_blk : STD_LOGIC;
    signal ap_ST_fsm_state12_blk : STD_LOGIC;
    signal ap_ST_fsm_state13_blk : STD_LOGIC;
    signal ap_ST_fsm_state14_blk : STD_LOGIC;
    signal mul_ln63_fu_207_p00 : STD_LOGIC_VECTOR (12 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component nn_fpga_top_nn_fpga_top_Pipeline_VITIS_LOOP_63_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        mul_ln65 : IN STD_LOGIC_VECTOR (12 downto 0);
        image_r_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        image_r_ce0 : OUT STD_LOGIC;
        image_r_we0 : OUT STD_LOGIC;
        image_r_d0 : OUT STD_LOGIC_VECTOR (9 downto 0) );
    end component;


    component nn_fpga_top_nn_fpga_top_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_47_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        h1_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        h1_ce0 : OUT STD_LOGIC;
        h1_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        output_r_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        output_r_ce0 : OUT STD_LOGIC;
        output_r_we0 : OUT STD_LOGIC;
        output_r_d0 : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component nn_fpga_top_nn_fpga_top_Pipeline_VITIS_LOOP_32_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        phi_mul : IN STD_LOGIC_VECTOR (15 downto 0);
        image_r_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        image_r_ce0 : OUT STD_LOGIC;
        image_r_q0 : IN STD_LOGIC_VECTOR (9 downto 0);
        acc_1_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        acc_1_out_ap_vld : OUT STD_LOGIC );
    end component;


    component nn_fpga_top_my_tanh IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        x : IN STD_LOGIC_VECTOR (15 downto 0);
        ap_return : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component nn_fpga_top_nn_fpga_top_Pipeline_VITIS_LOOP_77_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        max_val : IN STD_LOGIC_VECTOR (15 downto 0);
        output_r_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        output_r_ce0 : OUT STD_LOGIC;
        output_r_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        max_idx_out : OUT STD_LOGIC_VECTOR (3 downto 0);
        max_idx_out_ap_vld : OUT STD_LOGIC );
    end component;


    component nn_fpga_top_mul_4ns_11ns_13_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (3 downto 0);
        din1 : IN STD_LOGIC_VECTOR (10 downto 0);
        dout : OUT STD_LOGIC_VECTOR (12 downto 0) );
    end component;


    component nn_fpga_top_B1_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (5 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (4 downto 0) );
    end component;


    component nn_fpga_top_output_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (3 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (15 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component nn_fpga_top_image_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (9 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (9 downto 0) );
    end component;


    component nn_fpga_top_h1_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (5 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (15 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;



begin
    B1_U : component nn_fpga_top_B1_ROM_AUTO_1R
    generic map (
        DataWidth => 5,
        AddressRange => 64,
        AddressWidth => 6)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => B1_address0,
        ce0 => B1_ce0_local,
        q0 => B1_q0);

    output_U : component nn_fpga_top_output_RAM_AUTO_1R1W
    generic map (
        DataWidth => 16,
        AddressRange => 10,
        AddressWidth => 4)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => output_address0,
        ce0 => output_ce0,
        we0 => output_we0,
        d0 => grp_nn_fpga_top_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_47_2_fu_165_output_r_d0,
        q0 => output_q0);

    image_U : component nn_fpga_top_image_RAM_AUTO_1R1W
    generic map (
        DataWidth => 10,
        AddressRange => 784,
        AddressWidth => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => image_address0,
        ce0 => image_ce0,
        we0 => image_we0,
        d0 => grp_nn_fpga_top_Pipeline_VITIS_LOOP_63_1_fu_157_image_r_d0,
        q0 => image_q0);

    h1_U : component nn_fpga_top_h1_RAM_AUTO_1R1W
    generic map (
        DataWidth => 16,
        AddressRange => 64,
        AddressWidth => 6)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => h1_address0,
        ce0 => h1_ce0,
        we0 => h1_we0_local,
        d0 => grp_my_tanh_fu_184_ap_return,
        q0 => h1_q0);

    grp_nn_fpga_top_Pipeline_VITIS_LOOP_63_1_fu_157 : component nn_fpga_top_nn_fpga_top_Pipeline_VITIS_LOOP_63_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_nn_fpga_top_Pipeline_VITIS_LOOP_63_1_fu_157_ap_start,
        ap_done => grp_nn_fpga_top_Pipeline_VITIS_LOOP_63_1_fu_157_ap_done,
        ap_idle => grp_nn_fpga_top_Pipeline_VITIS_LOOP_63_1_fu_157_ap_idle,
        ap_ready => grp_nn_fpga_top_Pipeline_VITIS_LOOP_63_1_fu_157_ap_ready,
        mul_ln65 => mul_ln63_reg_304,
        image_r_address0 => grp_nn_fpga_top_Pipeline_VITIS_LOOP_63_1_fu_157_image_r_address0,
        image_r_ce0 => grp_nn_fpga_top_Pipeline_VITIS_LOOP_63_1_fu_157_image_r_ce0,
        image_r_we0 => grp_nn_fpga_top_Pipeline_VITIS_LOOP_63_1_fu_157_image_r_we0,
        image_r_d0 => grp_nn_fpga_top_Pipeline_VITIS_LOOP_63_1_fu_157_image_r_d0);

    grp_nn_fpga_top_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_47_2_fu_165 : component nn_fpga_top_nn_fpga_top_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_47_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_nn_fpga_top_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_47_2_fu_165_ap_start,
        ap_done => grp_nn_fpga_top_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_47_2_fu_165_ap_done,
        ap_idle => grp_nn_fpga_top_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_47_2_fu_165_ap_idle,
        ap_ready => grp_nn_fpga_top_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_47_2_fu_165_ap_ready,
        h1_address0 => grp_nn_fpga_top_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_47_2_fu_165_h1_address0,
        h1_ce0 => grp_nn_fpga_top_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_47_2_fu_165_h1_ce0,
        h1_q0 => h1_q0,
        output_r_address0 => grp_nn_fpga_top_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_47_2_fu_165_output_r_address0,
        output_r_ce0 => grp_nn_fpga_top_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_47_2_fu_165_output_r_ce0,
        output_r_we0 => grp_nn_fpga_top_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_47_2_fu_165_output_r_we0,
        output_r_d0 => grp_nn_fpga_top_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_47_2_fu_165_output_r_d0);

    grp_nn_fpga_top_Pipeline_VITIS_LOOP_32_2_fu_175 : component nn_fpga_top_nn_fpga_top_Pipeline_VITIS_LOOP_32_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_nn_fpga_top_Pipeline_VITIS_LOOP_32_2_fu_175_ap_start,
        ap_done => grp_nn_fpga_top_Pipeline_VITIS_LOOP_32_2_fu_175_ap_done,
        ap_idle => grp_nn_fpga_top_Pipeline_VITIS_LOOP_32_2_fu_175_ap_idle,
        ap_ready => grp_nn_fpga_top_Pipeline_VITIS_LOOP_32_2_fu_175_ap_ready,
        phi_mul => phi_mul_load_reg_309,
        image_r_address0 => grp_nn_fpga_top_Pipeline_VITIS_LOOP_32_2_fu_175_image_r_address0,
        image_r_ce0 => grp_nn_fpga_top_Pipeline_VITIS_LOOP_32_2_fu_175_image_r_ce0,
        image_r_q0 => image_q0,
        acc_1_out => grp_nn_fpga_top_Pipeline_VITIS_LOOP_32_2_fu_175_acc_1_out,
        acc_1_out_ap_vld => grp_nn_fpga_top_Pipeline_VITIS_LOOP_32_2_fu_175_acc_1_out_ap_vld);

    grp_my_tanh_fu_184 : component nn_fpga_top_my_tanh
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_my_tanh_fu_184_ap_start,
        ap_done => grp_my_tanh_fu_184_ap_done,
        ap_idle => grp_my_tanh_fu_184_ap_idle,
        ap_ready => grp_my_tanh_fu_184_ap_ready,
        x => acc_reg_337,
        ap_return => grp_my_tanh_fu_184_ap_return);

    grp_nn_fpga_top_Pipeline_VITIS_LOOP_77_2_fu_196 : component nn_fpga_top_nn_fpga_top_Pipeline_VITIS_LOOP_77_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_nn_fpga_top_Pipeline_VITIS_LOOP_77_2_fu_196_ap_start,
        ap_done => grp_nn_fpga_top_Pipeline_VITIS_LOOP_77_2_fu_196_ap_done,
        ap_idle => grp_nn_fpga_top_Pipeline_VITIS_LOOP_77_2_fu_196_ap_idle,
        ap_ready => grp_nn_fpga_top_Pipeline_VITIS_LOOP_77_2_fu_196_ap_ready,
        max_val => max_val_reg_347,
        output_r_address0 => grp_nn_fpga_top_Pipeline_VITIS_LOOP_77_2_fu_196_output_r_address0,
        output_r_ce0 => grp_nn_fpga_top_Pipeline_VITIS_LOOP_77_2_fu_196_output_r_ce0,
        output_r_q0 => output_q0,
        max_idx_out => grp_nn_fpga_top_Pipeline_VITIS_LOOP_77_2_fu_196_max_idx_out,
        max_idx_out_ap_vld => grp_nn_fpga_top_Pipeline_VITIS_LOOP_77_2_fu_196_max_idx_out_ap_vld);

    mul_4ns_11ns_13_1_1_U56 : component nn_fpga_top_mul_4ns_11ns_13_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 4,
        din1_WIDTH => 11,
        dout_WIDTH => 13)
    port map (
        din0 => mul_ln63_fu_207_p0,
        din1 => mul_ln63_fu_207_p1,
        dout => mul_ln63_fu_207_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_my_tanh_fu_184_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_my_tanh_fu_184_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
                    grp_my_tanh_fu_184_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_my_tanh_fu_184_ap_ready = ap_const_logic_1)) then 
                    grp_my_tanh_fu_184_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_nn_fpga_top_Pipeline_VITIS_LOOP_32_2_fu_175_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_nn_fpga_top_Pipeline_VITIS_LOOP_32_2_fu_175_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
                    grp_nn_fpga_top_Pipeline_VITIS_LOOP_32_2_fu_175_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_nn_fpga_top_Pipeline_VITIS_LOOP_32_2_fu_175_ap_ready = ap_const_logic_1)) then 
                    grp_nn_fpga_top_Pipeline_VITIS_LOOP_32_2_fu_175_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_nn_fpga_top_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_47_2_fu_165_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_nn_fpga_top_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_47_2_fu_165_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln29_fu_235_p2 = ap_const_lv1_1))) then 
                    grp_nn_fpga_top_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_47_2_fu_165_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_nn_fpga_top_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_47_2_fu_165_ap_ready = ap_const_logic_1)) then 
                    grp_nn_fpga_top_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_47_2_fu_165_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_nn_fpga_top_Pipeline_VITIS_LOOP_63_1_fu_157_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_nn_fpga_top_Pipeline_VITIS_LOOP_63_1_fu_157_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                    grp_nn_fpga_top_Pipeline_VITIS_LOOP_63_1_fu_157_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_nn_fpga_top_Pipeline_VITIS_LOOP_63_1_fu_157_ap_ready = ap_const_logic_1)) then 
                    grp_nn_fpga_top_Pipeline_VITIS_LOOP_63_1_fu_157_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_nn_fpga_top_Pipeline_VITIS_LOOP_77_2_fu_196_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_nn_fpga_top_Pipeline_VITIS_LOOP_77_2_fu_196_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
                    grp_nn_fpga_top_Pipeline_VITIS_LOOP_77_2_fu_196_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_nn_fpga_top_Pipeline_VITIS_LOOP_77_2_fu_196_ap_ready = ap_const_logic_1)) then 
                    grp_nn_fpga_top_Pipeline_VITIS_LOOP_77_2_fu_196_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    i_1_fu_82_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
                i_1_fu_82 <= ap_const_lv7_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln29_fu_235_p2 = ap_const_lv1_0))) then 
                i_1_fu_82 <= add_ln29_fu_241_p2;
            end if; 
        end if;
    end process;

    phi_mul_fu_78_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
                phi_mul_fu_78 <= ap_const_lv16_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln29_fu_235_p2 = ap_const_lv1_0))) then 
                phi_mul_fu_78 <= add_ln29_1_fu_229_p2;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state6)) then
                B1_load_reg_332 <= B1_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state7)) then
                acc_reg_337 <= acc_fu_267_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                i_reg_314 <= i_1_fu_82;
                phi_mul_load_reg_309 <= phi_mul_fu_78;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state13) and (grp_nn_fpga_top_Pipeline_VITIS_LOOP_77_2_fu_196_max_idx_out_ap_vld = ap_const_logic_1))) then
                max_idx_loc_fu_86 <= grp_nn_fpga_top_Pipeline_VITIS_LOOP_77_2_fu_196_max_idx_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state11)) then
                max_val_reg_347 <= output_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                mul_ln63_reg_304 <= mul_ln63_fu_207_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                    zext_ln29_reg_322(6 downto 0) <= zext_ln29_fu_257_p1(6 downto 0);
            end if;
        end if;
    end process;
    zext_ln29_reg_322(63 downto 7) <= "000000000000000000000000000000000000000000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state4, ap_CS_fsm_state6, grp_nn_fpga_top_Pipeline_VITIS_LOOP_63_1_fu_157_ap_done, grp_nn_fpga_top_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_47_2_fu_165_ap_done, grp_nn_fpga_top_Pipeline_VITIS_LOOP_32_2_fu_175_ap_done, grp_my_tanh_fu_184_ap_done, grp_nn_fpga_top_Pipeline_VITIS_LOOP_77_2_fu_196_ap_done, ap_CS_fsm_state3, icmp_ln29_fu_235_p2, ap_CS_fsm_state9, ap_CS_fsm_state8, ap_CS_fsm_state13)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                ap_NS_fsm <= ap_ST_fsm_state2;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_nn_fpga_top_Pipeline_VITIS_LOOP_63_1_fu_157_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln29_fu_235_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state9;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state6) and (grp_nn_fpga_top_Pipeline_VITIS_LOOP_32_2_fu_175_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state7;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state8) and (grp_my_tanh_fu_184_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state8;
                end if;
            when ap_ST_fsm_state9 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state9) and (grp_nn_fpga_top_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_47_2_fu_165_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state10;
                else
                    ap_NS_fsm <= ap_ST_fsm_state9;
                end if;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state11;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_state12;
            when ap_ST_fsm_state12 => 
                ap_NS_fsm <= ap_ST_fsm_state13;
            when ap_ST_fsm_state13 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state13) and (grp_nn_fpga_top_Pipeline_VITIS_LOOP_77_2_fu_196_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state14;
                else
                    ap_NS_fsm <= ap_ST_fsm_state13;
                end if;
            when ap_ST_fsm_state14 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXXX";
        end case;
    end process;
    B1_address0 <= zext_ln29_fu_257_p1(6 - 1 downto 0);

    B1_ce0_local_assign_proc : process(ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            B1_ce0_local <= ap_const_logic_1;
        else 
            B1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    acc_fu_267_p2 <= std_logic_vector(signed(sext_ln36_fu_264_p1) + signed(grp_nn_fpga_top_Pipeline_VITIS_LOOP_32_2_fu_175_acc_1_out));
    add_ln29_1_fu_229_p2 <= std_logic_vector(unsigned(phi_mul_fu_78) + unsigned(ap_const_lv16_310));
    add_ln29_fu_241_p2 <= std_logic_vector(unsigned(i_1_fu_82) + unsigned(ap_const_lv7_1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state11 <= ap_CS_fsm(10);
    ap_CS_fsm_state12 <= ap_CS_fsm(11);
    ap_CS_fsm_state13 <= ap_CS_fsm(12);
    ap_CS_fsm_state14 <= ap_CS_fsm(13);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);
    ap_ST_fsm_state10_blk <= ap_const_logic_0;
    ap_ST_fsm_state11_blk <= ap_const_logic_0;
    ap_ST_fsm_state12_blk <= ap_const_logic_0;

    ap_ST_fsm_state13_blk_assign_proc : process(grp_nn_fpga_top_Pipeline_VITIS_LOOP_77_2_fu_196_ap_done)
    begin
        if ((grp_nn_fpga_top_Pipeline_VITIS_LOOP_77_2_fu_196_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state13_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state13_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state14_blk <= ap_const_logic_0;
    ap_ST_fsm_state1_blk <= ap_const_logic_0;
    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_fsm_state3_blk_assign_proc : process(grp_nn_fpga_top_Pipeline_VITIS_LOOP_63_1_fu_157_ap_done)
    begin
        if ((grp_nn_fpga_top_Pipeline_VITIS_LOOP_63_1_fu_157_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;

    ap_ST_fsm_state6_blk_assign_proc : process(grp_nn_fpga_top_Pipeline_VITIS_LOOP_32_2_fu_175_ap_done)
    begin
        if ((grp_nn_fpga_top_Pipeline_VITIS_LOOP_32_2_fu_175_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state6_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state6_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state7_blk <= ap_const_logic_0;

    ap_ST_fsm_state8_blk_assign_proc : process(grp_my_tanh_fu_184_ap_done)
    begin
        if ((grp_my_tanh_fu_184_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state8_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state8_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state9_blk_assign_proc : process(grp_nn_fpga_top_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_47_2_fu_165_ap_done)
    begin
        if ((grp_nn_fpga_top_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_47_2_fu_165_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state9_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state9_blk <= ap_const_logic_0;
        end if; 
    end process;

    grp_my_tanh_fu_184_ap_start <= grp_my_tanh_fu_184_ap_start_reg;
    grp_nn_fpga_top_Pipeline_VITIS_LOOP_32_2_fu_175_ap_start <= grp_nn_fpga_top_Pipeline_VITIS_LOOP_32_2_fu_175_ap_start_reg;
    grp_nn_fpga_top_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_47_2_fu_165_ap_start <= grp_nn_fpga_top_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_47_2_fu_165_ap_start_reg;
    grp_nn_fpga_top_Pipeline_VITIS_LOOP_63_1_fu_157_ap_start <= grp_nn_fpga_top_Pipeline_VITIS_LOOP_63_1_fu_157_ap_start_reg;
    grp_nn_fpga_top_Pipeline_VITIS_LOOP_77_2_fu_196_ap_start <= grp_nn_fpga_top_Pipeline_VITIS_LOOP_77_2_fu_196_ap_start_reg;

    h1_address0_assign_proc : process(zext_ln29_reg_322, grp_nn_fpga_top_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_47_2_fu_165_h1_address0, ap_CS_fsm_state9)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            h1_address0 <= grp_nn_fpga_top_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_47_2_fu_165_h1_address0;
        else 
            h1_address0 <= zext_ln29_reg_322(6 - 1 downto 0);
        end if; 
    end process;


    h1_ce0_assign_proc : process(grp_nn_fpga_top_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_47_2_fu_165_h1_ce0, ap_CS_fsm_state9, h1_ce0_local)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            h1_ce0 <= grp_nn_fpga_top_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_47_2_fu_165_h1_ce0;
        else 
            h1_ce0 <= h1_ce0_local;
        end if; 
    end process;


    h1_ce0_local_assign_proc : process(grp_my_tanh_fu_184_ap_done, ap_CS_fsm_state8)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state8) and (grp_my_tanh_fu_184_ap_done = ap_const_logic_1))) then 
            h1_ce0_local <= ap_const_logic_1;
        else 
            h1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;


    h1_we0_local_assign_proc : process(grp_my_tanh_fu_184_ap_done, ap_CS_fsm_state8)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state8) and (grp_my_tanh_fu_184_ap_done = ap_const_logic_1))) then 
            h1_we0_local <= ap_const_logic_1;
        else 
            h1_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln29_fu_235_p2 <= "1" when (i_1_fu_82 = ap_const_lv7_40) else "0";

    image_address0_assign_proc : process(ap_CS_fsm_state6, grp_nn_fpga_top_Pipeline_VITIS_LOOP_63_1_fu_157_image_r_address0, grp_nn_fpga_top_Pipeline_VITIS_LOOP_32_2_fu_175_image_r_address0, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            image_address0 <= grp_nn_fpga_top_Pipeline_VITIS_LOOP_32_2_fu_175_image_r_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            image_address0 <= grp_nn_fpga_top_Pipeline_VITIS_LOOP_63_1_fu_157_image_r_address0;
        else 
            image_address0 <= "XXXXXXXXXX";
        end if; 
    end process;


    image_ce0_assign_proc : process(ap_CS_fsm_state6, grp_nn_fpga_top_Pipeline_VITIS_LOOP_63_1_fu_157_image_r_ce0, grp_nn_fpga_top_Pipeline_VITIS_LOOP_32_2_fu_175_image_r_ce0, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            image_ce0 <= grp_nn_fpga_top_Pipeline_VITIS_LOOP_32_2_fu_175_image_r_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            image_ce0 <= grp_nn_fpga_top_Pipeline_VITIS_LOOP_63_1_fu_157_image_r_ce0;
        else 
            image_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    image_we0_assign_proc : process(grp_nn_fpga_top_Pipeline_VITIS_LOOP_63_1_fu_157_image_r_we0, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            image_we0 <= grp_nn_fpga_top_Pipeline_VITIS_LOOP_63_1_fu_157_image_r_we0;
        else 
            image_we0 <= ap_const_logic_0;
        end if; 
    end process;

    led_out <= max_idx_loc_fu_86;
    mul_ln63_fu_207_p0 <= mul_ln63_fu_207_p00(4 - 1 downto 0);
    mul_ln63_fu_207_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(image_idx),13));
    mul_ln63_fu_207_p1 <= ap_const_lv13_310(11 - 1 downto 0);

    output_address0_assign_proc : process(grp_nn_fpga_top_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_47_2_fu_165_output_r_address0, grp_nn_fpga_top_Pipeline_VITIS_LOOP_77_2_fu_196_output_r_address0, ap_CS_fsm_state9, ap_CS_fsm_state13)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            output_address0 <= grp_nn_fpga_top_Pipeline_VITIS_LOOP_77_2_fu_196_output_r_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            output_address0 <= grp_nn_fpga_top_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_47_2_fu_165_output_r_address0;
        else 
            output_address0 <= ap_const_lv64_0(4 - 1 downto 0);
        end if; 
    end process;


    output_ce0_assign_proc : process(grp_nn_fpga_top_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_47_2_fu_165_output_r_ce0, grp_nn_fpga_top_Pipeline_VITIS_LOOP_77_2_fu_196_output_r_ce0, ap_CS_fsm_state9, ap_CS_fsm_state13, output_ce0_local)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            output_ce0 <= grp_nn_fpga_top_Pipeline_VITIS_LOOP_77_2_fu_196_output_r_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            output_ce0 <= grp_nn_fpga_top_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_47_2_fu_165_output_r_ce0;
        else 
            output_ce0 <= output_ce0_local;
        end if; 
    end process;


    output_ce0_local_assign_proc : process(ap_CS_fsm_state10)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            output_ce0_local <= ap_const_logic_1;
        else 
            output_ce0_local <= ap_const_logic_0;
        end if; 
    end process;


    output_we0_assign_proc : process(grp_nn_fpga_top_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_47_2_fu_165_output_r_we0, ap_CS_fsm_state9)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            output_we0 <= grp_nn_fpga_top_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_47_2_fu_165_output_r_we0;
        else 
            output_we0 <= ap_const_logic_0;
        end if; 
    end process;

        sext_ln36_fu_264_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(B1_load_reg_332),16));

    zext_ln29_fu_257_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_reg_314),64));
end behav;
