-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity nn_fpga_top_nn_fpga_top_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_47_2 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    h1_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    h1_ce0 : OUT STD_LOGIC;
    h1_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    output_r_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    output_r_ce0 : OUT STD_LOGIC;
    output_r_we0 : OUT STD_LOGIC;
    output_r_d0 : OUT STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of nn_fpga_top_nn_fpga_top_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_47_2 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv10_280 : STD_LOGIC_VECTOR (9 downto 0) := "1010000000";
    constant ap_const_lv10_1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv7_40 : STD_LOGIC_VECTOR (6 downto 0) := "1000000";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln45_fu_150_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal W2_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal W2_q0 : STD_LOGIC_VECTOR (8 downto 0);
    signal B2_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal B2_q0 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln47_fu_179_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln47_reg_345 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln47_reg_345_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln47_reg_345_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln47_reg_345_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln45_fu_185_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal select_ln45_reg_350 : STD_LOGIC_VECTOR (6 downto 0);
    signal select_ln45_1_fu_193_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln45_1_reg_356 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln45_1_reg_356_pp0_iter2_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln45_1_reg_356_pp0_iter3_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln45_1_reg_356_pp0_iter4_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal icmp_ln47_1_fu_207_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln47_1_reg_362 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln47_1_reg_362_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln47_1_reg_362_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln47_1_reg_362_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln47_1_reg_362_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal output_addr_reg_396 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln49_1_fu_243_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln47_fu_230_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln45_fu_259_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal acc_fu_60 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal acc_1_fu_279_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_sig_allocacmp_acc_load : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal j_fu_64 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    signal add_ln47_fu_201_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal i_2_fu_68 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal indvar_flatten_fu_72 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    signal add_ln45_1_fu_156_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_sig_allocacmp_indvar_flatten_load : STD_LOGIC_VECTOR (9 downto 0);
    signal h1_ce0_local : STD_LOGIC;
    signal W2_ce0_local : STD_LOGIC;
    signal B2_ce0_local : STD_LOGIC;
    signal output_r_we0_local : STD_LOGIC;
    signal acc_2_fu_292_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal output_r_ce0_local : STD_LOGIC;
    signal add_ln45_fu_173_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_fu_223_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln49_fu_234_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln49_1_fu_237_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln45_2_fu_264_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal acc_1_fu_279_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal grp_fu_304_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal sext_ln51_fu_288_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_304_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component nn_fpga_top_mac_muladd_16s_9s_24ns_24_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (8 downto 0);
        din2 : IN STD_LOGIC_VECTOR (23 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (23 downto 0) );
    end component;


    component nn_fpga_top_nn_fpga_top_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_47_2_W2_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (8 downto 0) );
    end component;


    component nn_fpga_top_nn_fpga_top_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_47_2_B2_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (3 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (6 downto 0) );
    end component;


    component nn_fpga_top_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    W2_U : component nn_fpga_top_nn_fpga_top_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_47_2_W2_ROM_AUTO_1R
    generic map (
        DataWidth => 9,
        AddressRange => 640,
        AddressWidth => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => W2_address0,
        ce0 => W2_ce0_local,
        q0 => W2_q0);

    B2_U : component nn_fpga_top_nn_fpga_top_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_47_2_B2_ROM_AUTO_1R
    generic map (
        DataWidth => 7,
        AddressRange => 10,
        AddressWidth => 4)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => B2_address0,
        ce0 => B2_ce0_local,
        q0 => B2_q0);

    mac_muladd_16s_9s_24ns_24_4_1_U47 : component nn_fpga_top_mac_muladd_16s_9s_24ns_24_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 9,
        din2_WIDTH => 24,
        dout_WIDTH => 24)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => h1_q0,
        din1 => W2_q0,
        din2 => grp_fu_304_p2,
        ce => ap_const_logic_1,
        dout => grp_fu_304_p3);

    flow_control_loop_pipe_sequential_init_U : component nn_fpga_top_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter5_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    acc_fu_60_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                    acc_fu_60 <= ap_const_lv16_0;
                elsif ((ap_enable_reg_pp0_iter6 = ap_const_logic_1)) then 
                    acc_fu_60 <= acc_1_fu_279_p1(23 downto 8);
                end if;
            end if; 
        end if;
    end process;

    i_2_fu_68_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    i_2_fu_68 <= ap_const_lv4_0;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    i_2_fu_68 <= select_ln45_1_fu_193_p3;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten_fu_72_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln45_fu_150_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    indvar_flatten_fu_72 <= add_ln45_1_fu_156_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten_fu_72 <= ap_const_lv10_0;
                end if;
            end if; 
        end if;
    end process;

    j_fu_64_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    j_fu_64 <= ap_const_lv7_0;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    j_fu_64 <= add_ln47_fu_201_p2;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                icmp_ln47_1_reg_362 <= icmp_ln47_1_fu_207_p2;
                icmp_ln47_reg_345 <= icmp_ln47_fu_179_p2;
                select_ln45_1_reg_356 <= select_ln45_1_fu_193_p3;
                select_ln45_reg_350 <= select_ln45_fu_185_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                icmp_ln47_1_reg_362_pp0_iter2_reg <= icmp_ln47_1_reg_362;
                icmp_ln47_1_reg_362_pp0_iter3_reg <= icmp_ln47_1_reg_362_pp0_iter2_reg;
                icmp_ln47_1_reg_362_pp0_iter4_reg <= icmp_ln47_1_reg_362_pp0_iter3_reg;
                icmp_ln47_1_reg_362_pp0_iter5_reg <= icmp_ln47_1_reg_362_pp0_iter4_reg;
                icmp_ln47_reg_345_pp0_iter2_reg <= icmp_ln47_reg_345;
                icmp_ln47_reg_345_pp0_iter3_reg <= icmp_ln47_reg_345_pp0_iter2_reg;
                icmp_ln47_reg_345_pp0_iter4_reg <= icmp_ln47_reg_345_pp0_iter3_reg;
                output_addr_reg_396 <= zext_ln45_fu_259_p1(4 - 1 downto 0);
                select_ln45_1_reg_356_pp0_iter2_reg <= select_ln45_1_reg_356;
                select_ln45_1_reg_356_pp0_iter3_reg <= select_ln45_1_reg_356_pp0_iter2_reg;
                select_ln45_1_reg_356_pp0_iter4_reg <= select_ln45_1_reg_356_pp0_iter3_reg;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    B2_address0 <= zext_ln45_fu_259_p1(4 - 1 downto 0);

    B2_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter5, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1))) then 
            B2_ce0_local <= ap_const_logic_1;
        else 
            B2_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    W2_address0 <= zext_ln49_1_fu_243_p1(10 - 1 downto 0);

    W2_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            W2_ce0_local <= ap_const_logic_1;
        else 
            W2_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    acc_1_fu_279_p1 <= grp_fu_304_p3;
    acc_1_fu_279_p4 <= acc_1_fu_279_p1(23 downto 8);
    acc_2_fu_292_p2 <= std_logic_vector(signed(sext_ln51_fu_288_p1) + signed(acc_1_fu_279_p4));
    add_ln45_1_fu_156_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten_load) + unsigned(ap_const_lv10_1));
    add_ln45_fu_173_p2 <= std_logic_vector(unsigned(i_2_fu_68) + unsigned(ap_const_lv4_1));
    add_ln47_fu_201_p2 <= std_logic_vector(unsigned(select_ln45_fu_185_p3) + unsigned(ap_const_lv7_1));
    add_ln49_1_fu_237_p2 <= std_logic_vector(unsigned(tmp_fu_223_p3) + unsigned(zext_ln49_fu_234_p1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln45_fu_150_p2)
    begin
        if (((icmp_ln45_fu_150_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter5_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter5_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6)
    begin
        if (((ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_acc_load_assign_proc : process(ap_enable_reg_pp0_iter6, ap_block_pp0_stage0, acc_fu_60, acc_1_fu_279_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1))) then 
            ap_sig_allocacmp_acc_load <= acc_1_fu_279_p1(23 downto 8);
        else 
            ap_sig_allocacmp_acc_load <= acc_fu_60;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten_fu_72)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_indvar_flatten_load <= ap_const_lv10_0;
        else 
            ap_sig_allocacmp_indvar_flatten_load <= indvar_flatten_fu_72;
        end if; 
    end process;

    grp_fu_304_p2 <= (select_ln45_2_fu_264_p3 & ap_const_lv8_0);
    h1_address0 <= zext_ln47_fu_230_p1(6 - 1 downto 0);
    h1_ce0 <= h1_ce0_local;

    h1_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            h1_ce0_local <= ap_const_logic_1;
        else 
            h1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln45_fu_150_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten_load = ap_const_lv10_280) else "0";
    icmp_ln47_1_fu_207_p2 <= "1" when (add_ln47_fu_201_p2 = ap_const_lv7_40) else "0";
    icmp_ln47_fu_179_p2 <= "1" when (j_fu_64 = ap_const_lv7_40) else "0";
    output_r_address0 <= output_addr_reg_396;
    output_r_ce0 <= output_r_ce0_local;

    output_r_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter6, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1))) then 
            output_r_ce0_local <= ap_const_logic_1;
        else 
            output_r_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    output_r_d0 <= acc_2_fu_292_p2;
    output_r_we0 <= output_r_we0_local;

    output_r_we0_local_assign_proc : process(ap_enable_reg_pp0_iter6, ap_block_pp0_stage0_11001, icmp_ln47_1_reg_362_pp0_iter5_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (icmp_ln47_1_reg_362_pp0_iter5_reg = ap_const_lv1_1))) then 
            output_r_we0_local <= ap_const_logic_1;
        else 
            output_r_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    select_ln45_1_fu_193_p3 <= 
        add_ln45_fu_173_p2 when (icmp_ln47_fu_179_p2(0) = '1') else 
        i_2_fu_68;
    select_ln45_2_fu_264_p3 <= 
        ap_const_lv16_0 when (icmp_ln47_reg_345_pp0_iter4_reg(0) = '1') else 
        ap_sig_allocacmp_acc_load;
    select_ln45_fu_185_p3 <= 
        ap_const_lv7_0 when (icmp_ln47_fu_179_p2(0) = '1') else 
        j_fu_64;
        sext_ln51_fu_288_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(B2_q0),16));

    tmp_fu_223_p3 <= (select_ln45_1_reg_356 & ap_const_lv6_0);
    zext_ln45_fu_259_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln45_1_reg_356_pp0_iter4_reg),64));
    zext_ln47_fu_230_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln45_reg_350),64));
    zext_ln49_1_fu_243_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln49_1_fu_237_p2),64));
    zext_ln49_fu_234_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln45_reg_350),10));
end behav;
