-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity nn_fpga_top_my_tanh is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    x : IN STD_LOGIC_VECTOR (15 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of nn_fpga_top_my_tanh is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (15 downto 0) := "0000000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (15 downto 0) := "0000000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (15 downto 0) := "0000000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (15 downto 0) := "0000001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (15 downto 0) := "0000010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (15 downto 0) := "0000100000000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (15 downto 0) := "0001000000000000";
    constant ap_ST_fsm_state14 : STD_LOGIC_VECTOR (15 downto 0) := "0010000000000000";
    constant ap_ST_fsm_state15 : STD_LOGIC_VECTOR (15 downto 0) := "0100000000000000";
    constant ap_ST_fsm_state16 : STD_LOGIC_VECTOR (15 downto 0) := "1000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv16_100 : STD_LOGIC_VECTOR (15 downto 0) := "0000000100000000";
    constant ap_const_lv16_FF00 : STD_LOGIC_VECTOR (15 downto 0) := "1111111100000000";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv64_3FF8000000000000 : STD_LOGIC_VECTOR (63 downto 0) := "0011111111111000000000000000000000000000000000000000000000000000";
    constant ap_const_lv64_BFF8000000000000 : STD_LOGIC_VECTOR (63 downto 0) := "1011111111111000000000000000000000000000000000000000000000000000";
    constant ap_const_lv5_10 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv6_36 : STD_LOGIC_VECTOR (5 downto 0) := "110110";
    constant ap_const_lv5_8 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv32_36 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110110";
    constant ap_const_lv11_3FF : STD_LOGIC_VECTOR (10 downto 0) := "01111111111";
    constant ap_const_lv11_3FE : STD_LOGIC_VECTOR (10 downto 0) := "01111111110";
    constant ap_const_lv32_34 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110100";
    constant ap_const_lv5_19 : STD_LOGIC_VECTOR (4 downto 0) := "11001";
    constant ap_const_lv32_27 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100111";
    constant ap_const_lv32_19 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011001";
    constant ap_const_lv8_7F : STD_LOGIC_VECTOR (7 downto 0) := "01111111";
    constant ap_const_lv8_7E : STD_LOGIC_VECTOR (7 downto 0) := "01111110";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv54_0 : STD_LOGIC_VECTOR (53 downto 0) := "000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv63_0 : STD_LOGIC_VECTOR (62 downto 0) := "000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv12_433 : STD_LOGIC_VECTOR (11 downto 0) := "010000110011";
    constant ap_const_lv12_8 : STD_LOGIC_VECTOR (11 downto 0) := "000000001000";
    constant ap_const_lv11_7F8 : STD_LOGIC_VECTOR (10 downto 0) := "11111111000";
    constant ap_const_lv11_8 : STD_LOGIC_VECTOR (10 downto 0) := "00000001000";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv11_36 : STD_LOGIC_VECTOR (10 downto 0) := "00000110110";
    constant ap_const_lv16_FFFF : STD_LOGIC_VECTOR (15 downto 0) := "1111111111111111";
    constant ap_const_lv5_2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_const_lv5_4 : STD_LOGIC_VECTOR (4 downto 0) := "00100";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal icmp_ln16_fu_173_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln16_reg_565 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_fu_179_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_reg_569 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln16_fu_193_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln16_reg_575 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln16_fu_212_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln16_reg_582 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal sub_ln16_2_fu_216_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal sub_ln16_2_reg_587 : STD_LOGIC_VECTOR (4 downto 0);
    signal sub_ln16_3_fu_226_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal sub_ln16_3_reg_592 : STD_LOGIC_VECTOR (5 downto 0);
    signal sub_ln16_1_fu_232_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal sub_ln16_1_reg_597 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal LD_fu_296_p5 : STD_LOGIC_VECTOR (63 downto 0);
    signal LD_reg_602 : STD_LOGIC_VECTOR (63 downto 0);
    signal bitcast_ln767_fu_308_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal bitcast_ln767_reg_607 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal zext_ln16_4_fu_312_p1 : STD_LOGIC_VECTOR (39 downto 0);
    signal zext_ln16_4_reg_612 : STD_LOGIC_VECTOR (39 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal grp_fu_167_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_9_reg_617 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_s_reg_621 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal sub_ln22_fu_315_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal sub_ln22_reg_625 : STD_LOGIC_VECTOR (4 downto 0);
    signal LD_1_fu_386_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal LD_1_reg_630 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal bitcast_ln777_fu_390_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal grp_generic_tanh_float_s_fu_151_ap_return : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal trunc_ln22_fu_397_p1 : STD_LOGIC_VECTOR (62 downto 0);
    signal trunc_ln22_reg_645 : STD_LOGIC_VECTOR (62 downto 0);
    signal ap_CS_fsm_state11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state11 : signal is "none";
    signal tmp_8_reg_650 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_7_reg_656 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln22_1_fu_417_p1 : STD_LOGIC_VECTOR (51 downto 0);
    signal trunc_ln22_1_reg_661 : STD_LOGIC_VECTOR (51 downto 0);
    signal select_ln22_1_fu_441_p3 : STD_LOGIC_VECTOR (53 downto 0);
    signal select_ln22_1_reg_666 : STD_LOGIC_VECTOR (53 downto 0);
    signal ap_CS_fsm_state12 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state12 : signal is "none";
    signal icmp_ln22_fu_448_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln22_reg_673 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln22_1_fu_463_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln22_1_reg_677 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln22_2_fu_481_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln22_2_reg_681 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln22_2_fu_489_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln22_2_reg_689 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln22_4_fu_522_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state13 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state13 : signal is "none";
    signal select_ln22_3_fu_554_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln22_3_reg_698 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state14 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state14 : signal is "none";
    signal trunc_ln22_3_fu_562_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state16 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state16 : signal is "none";
    signal grp_generic_tanh_float_s_fu_151_ap_start : STD_LOGIC;
    signal grp_generic_tanh_float_s_fu_151_ap_done : STD_LOGIC;
    signal grp_generic_tanh_float_s_fu_151_ap_idle : STD_LOGIC;
    signal grp_generic_tanh_float_s_fu_151_ap_ready : STD_LOGIC;
    signal x_assign_reg_116 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_agg_result_0_phi_fu_134_p12 : STD_LOGIC_VECTOR (15 downto 0);
    signal agg_result_0_reg_128 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state15 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state15 : signal is "none";
    signal grp_generic_tanh_float_s_fu_151_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal grp_fu_167_p0 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_167_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal sub_ln16_fu_187_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_1_fu_201_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln16_fu_208_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln16_3_fu_222_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln16_1_fu_237_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln16_2_fu_240_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal shl_ln16_fu_243_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal lshr_ln_fu_249_p4 : STD_LOGIC_VECTOR (62 downto 0);
    signal tmp_4_fu_263_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln16_1_fu_271_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln16_fu_279_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln16_fu_283_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln16_5_fu_259_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_2_fu_289_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln22_fu_320_p1 : STD_LOGIC_VECTOR (39 downto 0);
    signal shl_ln22_fu_323_p2 : STD_LOGIC_VECTOR (39 downto 0);
    signal lshr_ln1_fu_328_p4 : STD_LOGIC_VECTOR (38 downto 0);
    signal tmp_6_fu_342_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln22_fu_350_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln22_fu_358_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln22_fu_361_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln22_2_fu_338_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_3_fu_367_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal pi_assign_fu_374_p5 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_163_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal bitcast_ln735_fu_393_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln22_4_cast_fu_424_p3 : STD_LOGIC_VECTOR (52 downto 0);
    signal zext_ln22_4_fu_431_p1 : STD_LOGIC_VECTOR (53 downto 0);
    signal sub_ln22_1_fu_435_p2 : STD_LOGIC_VECTOR (53 downto 0);
    signal zext_ln22_1_fu_421_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal sub_ln22_2_fu_453_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal trunc_ln22_2_fu_459_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln22_1_fu_469_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal sub_ln22_3_fu_475_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_10_fu_498_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln22_5_fu_495_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln22_2cast_fu_513_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln22_4_fu_507_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln22_1_fu_516_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln22_3_fu_542_p1 : STD_LOGIC_VECTOR (53 downto 0);
    signal ashr_ln22_fu_545_p2 : STD_LOGIC_VECTOR (53 downto 0);
    signal icmp_ln22_3_fu_530_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln22_4_fu_550_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln22_5_fu_535_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_163_ce : STD_LOGIC;
    signal grp_fu_167_opcode : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_return_preg : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_ST_fsm_state11_blk : STD_LOGIC;
    signal ap_ST_fsm_state12_blk : STD_LOGIC;
    signal ap_ST_fsm_state13_blk : STD_LOGIC;
    signal ap_ST_fsm_state14_blk : STD_LOGIC;
    signal ap_ST_fsm_state15_blk : STD_LOGIC;
    signal ap_ST_fsm_state16_blk : STD_LOGIC;
    signal tmp_1_fu_201_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_1_fu_201_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component nn_fpga_top_generic_tanh_float_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        t_in : IN STD_LOGIC_VECTOR (31 downto 0);
        ap_return : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component nn_fpga_top_fpext_32ns_64_2_no_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component nn_fpga_top_dcmp_64ns_64ns_1_2_no_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (63 downto 0);
        din1 : IN STD_LOGIC_VECTOR (63 downto 0);
        ce : IN STD_LOGIC;
        opcode : IN STD_LOGIC_VECTOR (4 downto 0);
        dout : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component nn_fpga_top_ctlz_16_16_1_1 IS
    generic (
        din_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din : IN STD_LOGIC_VECTOR (15 downto 0);
        dout : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;



begin
    grp_generic_tanh_float_s_fu_151 : component nn_fpga_top_generic_tanh_float_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_generic_tanh_float_s_fu_151_ap_start,
        ap_done => grp_generic_tanh_float_s_fu_151_ap_done,
        ap_idle => grp_generic_tanh_float_s_fu_151_ap_idle,
        ap_ready => grp_generic_tanh_float_s_fu_151_ap_ready,
        t_in => x_assign_reg_116,
        ap_return => grp_generic_tanh_float_s_fu_151_ap_return);

    fpext_32ns_64_2_no_dsp_1_U41 : component nn_fpga_top_fpext_32ns_64_2_no_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        dout_WIDTH => 64)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_generic_tanh_float_s_fu_151_ap_return,
        ce => grp_fu_163_ce,
        dout => grp_fu_163_p1);

    dcmp_64ns_64ns_1_2_no_dsp_1_U42 : component nn_fpga_top_dcmp_64ns_64ns_1_2_no_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 64,
        din1_WIDTH => 64,
        dout_WIDTH => 1)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_167_p0,
        din1 => grp_fu_167_p1,
        ce => ap_const_logic_1,
        opcode => grp_fu_167_opcode,
        dout => grp_fu_167_p2);

    ctlz_16_16_1_1_U43 : component nn_fpga_top_ctlz_16_16_1_1
    generic map (
        din_WIDTH => 16,
        dout_WIDTH => 16)
    port map (
        din => select_ln16_reg_575,
        dout => tmp_1_fu_201_p3);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_return_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_preg <= ap_const_lv16_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state15)) then 
                    ap_return_preg <= ap_phi_mux_agg_result_0_phi_fu_134_p12;
                end if; 
            end if;
        end if;
    end process;


    grp_generic_tanh_float_s_fu_151_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_generic_tanh_float_s_fu_151_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
                    grp_generic_tanh_float_s_fu_151_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_generic_tanh_float_s_fu_151_ap_ready = ap_const_logic_1)) then 
                    grp_generic_tanh_float_s_fu_151_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    agg_result_0_reg_128_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state12) and (icmp_ln22_fu_448_p2 = ap_const_lv1_1))) then 
                agg_result_0_reg_128 <= ap_const_lv16_0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
                agg_result_0_reg_128 <= select_ln22_4_fu_522_p3;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state15) and (((icmp_ln16_reg_565 = ap_const_lv1_1) and (icmp_ln22_2_reg_689 = ap_const_lv1_0) and (icmp_ln22_1_reg_677 = ap_const_lv1_1) and (icmp_ln22_reg_673 = ap_const_lv1_0)) or ((tmp_s_reg_621 = ap_const_lv1_0) and (tmp_9_reg_617 = ap_const_lv1_0) and (icmp_ln22_2_reg_689 = ap_const_lv1_0) and (icmp_ln22_1_reg_677 = ap_const_lv1_1) and (icmp_ln22_reg_673 = ap_const_lv1_0))))) then 
                agg_result_0_reg_128 <= select_ln22_3_reg_698;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state16)) then 
                agg_result_0_reg_128 <= trunc_ln22_3_fu_562_p1;
            elsif (((grp_fu_167_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
                agg_result_0_reg_128 <= ap_const_lv16_FF00;
            elsif (((grp_fu_167_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                agg_result_0_reg_128 <= ap_const_lv16_100;
            end if; 
        end if;
    end process;

    x_assign_reg_116_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln16_fu_173_p2 = ap_const_lv1_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                x_assign_reg_116 <= ap_const_lv32_0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
                x_assign_reg_116 <= bitcast_ln777_fu_390_p1;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state7)) then
                LD_1_reg_630 <= LD_1_fu_386_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                LD_reg_602 <= LD_fu_296_p5;
                sub_ln16_1_reg_597 <= sub_ln16_1_fu_232_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                bitcast_ln767_reg_607 <= bitcast_ln767_fu_308_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                icmp_ln16_reg_565 <= icmp_ln16_fu_173_p2;
                select_ln16_reg_575 <= select_ln16_fu_193_p3;
                tmp_reg_569 <= x(15 downto 15);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state12)) then
                icmp_ln22_1_reg_677 <= icmp_ln22_1_fu_463_p2;
                icmp_ln22_2_reg_689 <= icmp_ln22_2_fu_489_p2;
                icmp_ln22_reg_673 <= icmp_ln22_fu_448_p2;
                select_ln22_1_reg_666 <= select_ln22_1_fu_441_p3;
                select_ln22_2_reg_681 <= select_ln22_2_fu_481_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state14)) then
                select_ln22_3_reg_698 <= select_ln22_3_fu_554_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                sub_ln16_2_reg_587 <= sub_ln16_2_fu_216_p2;
                sub_ln16_3_reg_592 <= sub_ln16_3_fu_226_p2;
                    zext_ln16_reg_582(3 downto 0) <= zext_ln16_fu_212_p1(3 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state6)) then
                sub_ln22_reg_625 <= sub_ln22_fu_315_p2;
                tmp_s_reg_621 <= grp_fu_167_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state11)) then
                tmp_7_reg_656 <= bitcast_ln735_fu_393_p1(62 downto 52);
                tmp_8_reg_650 <= bitcast_ln735_fu_393_p1(63 downto 63);
                trunc_ln22_1_reg_661 <= trunc_ln22_1_fu_417_p1;
                trunc_ln22_reg_645 <= trunc_ln22_fu_397_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                tmp_9_reg_617 <= grp_fu_167_p2;
                    zext_ln16_4_reg_612(15 downto 0) <= zext_ln16_4_fu_312_p1(15 downto 0);
            end if;
        end if;
    end process;
    zext_ln16_reg_582(4) <= '0';
    zext_ln16_4_reg_612(39 downto 16) <= "000000000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, icmp_ln16_fu_173_p2, ap_CS_fsm_state5, grp_fu_167_p2, ap_CS_fsm_state6, ap_CS_fsm_state10, ap_CS_fsm_state12, icmp_ln22_fu_448_p2, icmp_ln22_1_fu_463_p2, icmp_ln22_2_fu_489_p2, grp_generic_tanh_float_s_fu_151_ap_done)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((icmp_ln16_fu_173_p2 = ap_const_lv1_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state9;
                elsif (((icmp_ln16_fu_173_p2 = ap_const_lv1_0) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                if (((grp_fu_167_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                    ap_NS_fsm <= ap_ST_fsm_state15;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when ap_ST_fsm_state6 => 
                if (((grp_fu_167_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then
                    ap_NS_fsm <= ap_ST_fsm_state15;
                else
                    ap_NS_fsm <= ap_ST_fsm_state7;
                end if;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state10) and (grp_generic_tanh_float_s_fu_151_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state11;
                else
                    ap_NS_fsm <= ap_ST_fsm_state10;
                end if;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_state12;
            when ap_ST_fsm_state12 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state12) and (icmp_ln22_2_fu_489_p2 = ap_const_lv1_0) and (icmp_ln22_1_fu_463_p2 = ap_const_lv1_1) and (icmp_ln22_fu_448_p2 = ap_const_lv1_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state14;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state12) and (icmp_ln22_2_fu_489_p2 = ap_const_lv1_0) and (icmp_ln22_1_fu_463_p2 = ap_const_lv1_0) and (icmp_ln22_fu_448_p2 = ap_const_lv1_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state13;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state12) and (icmp_ln22_2_fu_489_p2 = ap_const_lv1_1) and (icmp_ln22_fu_448_p2 = ap_const_lv1_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state16;
                else
                    ap_NS_fsm <= ap_ST_fsm_state15;
                end if;
            when ap_ST_fsm_state13 => 
                ap_NS_fsm <= ap_ST_fsm_state15;
            when ap_ST_fsm_state14 => 
                ap_NS_fsm <= ap_ST_fsm_state15;
            when ap_ST_fsm_state15 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when ap_ST_fsm_state16 => 
                ap_NS_fsm <= ap_ST_fsm_state15;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXXXXX";
        end case;
    end process;
    LD_1_fu_386_p1 <= pi_assign_fu_374_p5(32 - 1 downto 0);
    LD_fu_296_p5 <= (tmp_2_fu_289_p3 & zext_ln16_5_fu_259_p1(51 downto 0));
    add_ln16_fu_283_p2 <= std_logic_vector(unsigned(select_ln16_1_fu_271_p3) + unsigned(sext_ln16_fu_279_p1));
    add_ln22_1_fu_469_p2 <= std_logic_vector(unsigned(trunc_ln22_2_fu_459_p1) + unsigned(ap_const_lv11_7F8));
    add_ln22_fu_361_p2 <= std_logic_vector(unsigned(select_ln22_fu_350_p3) + unsigned(sext_ln22_fu_358_p1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state11 <= ap_CS_fsm(10);
    ap_CS_fsm_state12 <= ap_CS_fsm(11);
    ap_CS_fsm_state13 <= ap_CS_fsm(12);
    ap_CS_fsm_state14 <= ap_CS_fsm(13);
    ap_CS_fsm_state15 <= ap_CS_fsm(14);
    ap_CS_fsm_state16 <= ap_CS_fsm(15);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);

    ap_ST_fsm_state10_blk_assign_proc : process(grp_generic_tanh_float_s_fu_151_ap_done)
    begin
        if ((grp_generic_tanh_float_s_fu_151_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state10_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state10_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state11_blk <= ap_const_logic_0;
    ap_ST_fsm_state12_blk <= ap_const_logic_0;
    ap_ST_fsm_state13_blk <= ap_const_logic_0;
    ap_ST_fsm_state14_blk <= ap_const_logic_0;
    ap_ST_fsm_state15_blk <= ap_const_logic_0;
    ap_ST_fsm_state16_blk <= ap_const_logic_0;

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;
    ap_ST_fsm_state7_blk <= ap_const_logic_0;
    ap_ST_fsm_state8_blk <= ap_const_logic_0;
    ap_ST_fsm_state9_blk <= ap_const_logic_0;

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state15)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state15) or ((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_agg_result_0_phi_fu_134_p12_assign_proc : process(icmp_ln16_reg_565, tmp_9_reg_617, tmp_s_reg_621, icmp_ln22_reg_673, icmp_ln22_1_reg_677, icmp_ln22_2_reg_689, select_ln22_3_reg_698, agg_result_0_reg_128, ap_CS_fsm_state15)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state15) and (((icmp_ln16_reg_565 = ap_const_lv1_1) and (icmp_ln22_2_reg_689 = ap_const_lv1_0) and (icmp_ln22_1_reg_677 = ap_const_lv1_1) and (icmp_ln22_reg_673 = ap_const_lv1_0)) or ((tmp_s_reg_621 = ap_const_lv1_0) and (tmp_9_reg_617 = ap_const_lv1_0) and (icmp_ln22_2_reg_689 = ap_const_lv1_0) and (icmp_ln22_1_reg_677 = ap_const_lv1_1) and (icmp_ln22_reg_673 = ap_const_lv1_0))))) then 
            ap_phi_mux_agg_result_0_phi_fu_134_p12 <= select_ln22_3_reg_698;
        else 
            ap_phi_mux_agg_result_0_phi_fu_134_p12 <= agg_result_0_reg_128;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state15)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state15)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_return_assign_proc : process(ap_phi_mux_agg_result_0_phi_fu_134_p12, ap_CS_fsm_state15, ap_return_preg)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state15)) then 
            ap_return <= ap_phi_mux_agg_result_0_phi_fu_134_p12;
        else 
            ap_return <= ap_return_preg;
        end if; 
    end process;

    ashr_ln22_fu_545_p2 <= std_logic_vector(shift_right(signed(select_ln22_1_reg_666),to_integer(unsigned('0' & zext_ln22_3_fu_542_p1(31-1 downto 0)))));
    bitcast_ln735_fu_393_p1 <= grp_fu_163_p1;
    bitcast_ln767_fu_308_p1 <= LD_reg_602;
    bitcast_ln777_fu_390_p1 <= LD_1_reg_630;

    grp_fu_163_ce_assign_proc : process(ap_CS_fsm_state10, ap_CS_fsm_state11, grp_generic_tanh_float_s_fu_151_ap_done)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state11) or ((ap_const_logic_1 = ap_CS_fsm_state10) and (grp_generic_tanh_float_s_fu_151_ap_done = ap_const_logic_1)))) then 
            grp_fu_163_ce <= ap_const_logic_1;
        else 
            grp_fu_163_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_167_opcode_assign_proc : process(ap_CS_fsm_state4, ap_CS_fsm_state5, grp_fu_167_p2)
    begin
        if (((grp_fu_167_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            grp_fu_167_opcode <= ap_const_lv5_4;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            grp_fu_167_opcode <= ap_const_lv5_2;
        else 
            grp_fu_167_opcode <= "XXXXX";
        end if; 
    end process;


    grp_fu_167_p0_assign_proc : process(bitcast_ln767_fu_308_p1, bitcast_ln767_reg_607, ap_CS_fsm_state4, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            grp_fu_167_p0 <= bitcast_ln767_reg_607;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            grp_fu_167_p0 <= bitcast_ln767_fu_308_p1;
        else 
            grp_fu_167_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_167_p1_assign_proc : process(ap_CS_fsm_state4, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            grp_fu_167_p1 <= ap_const_lv64_BFF8000000000000;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            grp_fu_167_p1 <= ap_const_lv64_3FF8000000000000;
        else 
            grp_fu_167_p1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    grp_generic_tanh_float_s_fu_151_ap_start <= grp_generic_tanh_float_s_fu_151_ap_start_reg;
    icmp_ln16_fu_173_p2 <= "1" when (x = ap_const_lv16_0) else "0";
    icmp_ln22_1_fu_463_p2 <= "1" when (signed(sub_ln22_2_fu_453_p2) > signed(ap_const_lv12_8)) else "0";
    icmp_ln22_2_fu_489_p2 <= "1" when (sub_ln22_2_fu_453_p2 = ap_const_lv12_8) else "0";
    icmp_ln22_3_fu_530_p2 <= "1" when (unsigned(select_ln22_2_reg_681) < unsigned(ap_const_lv11_36)) else "0";
    icmp_ln22_4_fu_507_p2 <= "1" when (tmp_10_fu_498_p4 = ap_const_lv7_0) else "0";
    icmp_ln22_fu_448_p2 <= "1" when (trunc_ln22_reg_645 = ap_const_lv63_0) else "0";
    lshr_ln1_fu_328_p4 <= shl_ln22_fu_323_p2(39 downto 1);
    lshr_ln_fu_249_p4 <= shl_ln16_fu_243_p2(63 downto 1);
    pi_assign_fu_374_p5 <= (zext_ln22_2_fu_338_p1(63 downto 32) & tmp_3_fu_367_p3 & zext_ln22_2_fu_338_p1(22 downto 0));
    select_ln16_1_fu_271_p3 <= 
        ap_const_lv11_3FF when (tmp_4_fu_263_p3(0) = '1') else 
        ap_const_lv11_3FE;
    select_ln16_fu_193_p3 <= 
        sub_ln16_fu_187_p2 when (tmp_fu_179_p3(0) = '1') else 
        x;
    select_ln22_1_fu_441_p3 <= 
        sub_ln22_1_fu_435_p2 when (tmp_8_reg_650(0) = '1') else 
        zext_ln22_4_fu_431_p1;
    select_ln22_2_fu_481_p3 <= 
        add_ln22_1_fu_469_p2 when (icmp_ln22_1_fu_463_p2(0) = '1') else 
        sub_ln22_3_fu_475_p2;
    select_ln22_2cast_fu_513_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln22_2_reg_681),16));
    select_ln22_3_fu_554_p3 <= 
        trunc_ln22_4_fu_550_p1 when (icmp_ln22_3_fu_530_p2(0) = '1') else 
        select_ln22_5_fu_535_p3;
    select_ln22_4_fu_522_p3 <= 
        shl_ln22_1_fu_516_p2 when (icmp_ln22_4_fu_507_p2(0) = '1') else 
        ap_const_lv16_0;
    select_ln22_5_fu_535_p3 <= 
        ap_const_lv16_FFFF when (tmp_8_reg_650(0) = '1') else 
        ap_const_lv16_0;
    select_ln22_fu_350_p3 <= 
        ap_const_lv8_7F when (tmp_6_fu_342_p3(0) = '1') else 
        ap_const_lv8_7E;
        sext_ln16_fu_279_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln16_1_fu_232_p2),11));

        sext_ln22_fu_358_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln16_1_reg_597),8));

    shl_ln16_fu_243_p2 <= std_logic_vector(shift_left(unsigned(zext_ln16_1_fu_237_p1),to_integer(unsigned('0' & zext_ln16_2_fu_240_p1(31-1 downto 0)))));
    shl_ln22_1_fu_516_p2 <= std_logic_vector(shift_left(unsigned(trunc_ln22_5_fu_495_p1),to_integer(unsigned('0' & select_ln22_2cast_fu_513_p1(16-1 downto 0)))));
    shl_ln22_fu_323_p2 <= std_logic_vector(shift_left(unsigned(zext_ln16_4_reg_612),to_integer(unsigned('0' & zext_ln22_fu_320_p1(31-1 downto 0)))));
    sub_ln16_1_fu_232_p2 <= std_logic_vector(unsigned(ap_const_lv5_8) - unsigned(zext_ln16_reg_582));
    sub_ln16_2_fu_216_p2 <= std_logic_vector(signed(ap_const_lv5_10) - signed(zext_ln16_fu_212_p1));
    sub_ln16_3_fu_226_p2 <= std_logic_vector(signed(ap_const_lv6_36) - signed(zext_ln16_3_fu_222_p1));
    sub_ln16_fu_187_p2 <= std_logic_vector(unsigned(ap_const_lv16_0) - unsigned(x));
    sub_ln22_1_fu_435_p2 <= std_logic_vector(unsigned(ap_const_lv54_0) - unsigned(zext_ln22_4_fu_431_p1));
    sub_ln22_2_fu_453_p2 <= std_logic_vector(unsigned(ap_const_lv12_433) - unsigned(zext_ln22_1_fu_421_p1));
    sub_ln22_3_fu_475_p2 <= std_logic_vector(unsigned(ap_const_lv11_8) - unsigned(trunc_ln22_2_fu_459_p1));
    sub_ln22_fu_315_p2 <= std_logic_vector(signed(ap_const_lv5_19) - signed(sub_ln16_2_reg_587));
    tmp_10_fu_498_p4 <= select_ln22_2_reg_681(10 downto 4);
    tmp_2_fu_289_p3 <= (tmp_reg_569 & add_ln16_fu_283_p2);
    tmp_3_fu_367_p3 <= (tmp_reg_569 & add_ln22_fu_361_p2);
    tmp_4_fu_263_p3 <= shl_ln16_fu_243_p2(54 downto 54);
    tmp_6_fu_342_p3 <= shl_ln22_fu_323_p2(25 downto 25);
    tmp_fu_179_p3 <= x(15 downto 15);
    trunc_ln16_fu_208_p1 <= tmp_1_fu_201_p3(4 - 1 downto 0);
    trunc_ln22_1_fu_417_p1 <= bitcast_ln735_fu_393_p1(52 - 1 downto 0);
    trunc_ln22_2_fu_459_p1 <= sub_ln22_2_fu_453_p2(11 - 1 downto 0);
    trunc_ln22_3_fu_562_p1 <= select_ln22_1_reg_666(16 - 1 downto 0);
    trunc_ln22_4_fu_550_p1 <= ashr_ln22_fu_545_p2(16 - 1 downto 0);
    trunc_ln22_5_fu_495_p1 <= select_ln22_1_reg_666(16 - 1 downto 0);
    trunc_ln22_fu_397_p1 <= bitcast_ln735_fu_393_p1(63 - 1 downto 0);
    zext_ln16_1_fu_237_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln16_reg_575),64));
    zext_ln16_2_fu_240_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sub_ln16_3_reg_592),64));
    zext_ln16_3_fu_222_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sub_ln16_2_fu_216_p2),6));
    zext_ln16_4_fu_312_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln16_reg_575),40));
    zext_ln16_5_fu_259_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln_fu_249_p4),64));
    zext_ln16_fu_212_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln16_fu_208_p1),5));
    zext_ln22_1_fu_421_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_7_reg_656),12));
    zext_ln22_2_fu_338_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln1_fu_328_p4),64));
    zext_ln22_3_fu_542_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln22_2_reg_681),54));
    zext_ln22_4_cast_fu_424_p3 <= (ap_const_lv1_1 & trunc_ln22_1_reg_661);
    zext_ln22_4_fu_431_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln22_4_cast_fu_424_p3),54));
    zext_ln22_fu_320_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sub_ln22_reg_625),40));
end behav;
