# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/unnath/Projects/vivado_and_vitis/final_nn_fpga_tanh/final_nn_fpga_tanh/hls/impl/verilog/project.srcs/sources_1/bd/bd_0/ip/bd_0_hls_inst_0/bd_0_hls_inst_0.xci
# IP: The module: 'bd_0_hls_inst_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/unnath/Projects/vivado_and_vitis/final_nn_fpga_tanh/final_nn_fpga_tanh/hls/impl/verilog/project.gen/sources_1/bd/bd_0/ip/bd_0_hls_inst_0/hdl/ip/nn_fpga_top_dadd_64ns_64ns_64_8_full_dsp_1_ip/nn_fpga_top_dadd_64ns_64ns_64_8_full_dsp_1_ip.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==nn_fpga_top_dadd_64ns_64ns_64_8_full_dsp_1_ip || ORIG_REF_NAME==nn_fpga_top_dadd_64ns_64ns_64_8_full_dsp_1_ip} -quiet] -quiet

# IP: /home/unnath/Projects/vivado_and_vitis/final_nn_fpga_tanh/final_nn_fpga_tanh/hls/impl/verilog/project.gen/sources_1/bd/bd_0/ip/bd_0_hls_inst_0/hdl/ip/nn_fpga_top_dcmp_64ns_64ns_1_2_no_dsp_1_ip/nn_fpga_top_dcmp_64ns_64ns_1_2_no_dsp_1_ip.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==nn_fpga_top_dcmp_64ns_64ns_1_2_no_dsp_1_ip || ORIG_REF_NAME==nn_fpga_top_dcmp_64ns_64ns_1_2_no_dsp_1_ip} -quiet] -quiet

# IP: /home/unnath/Projects/vivado_and_vitis/final_nn_fpga_tanh/final_nn_fpga_tanh/hls/impl/verilog/project.gen/sources_1/bd/bd_0/ip/bd_0_hls_inst_0/hdl/ip/nn_fpga_top_faddfsub_32ns_32ns_32_7_full_dsp_1_ip/nn_fpga_top_faddfsub_32ns_32ns_32_7_full_dsp_1_ip.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==nn_fpga_top_faddfsub_32ns_32ns_32_7_full_dsp_1_ip || ORIG_REF_NAME==nn_fpga_top_faddfsub_32ns_32ns_32_7_full_dsp_1_ip} -quiet] -quiet

# IP: /home/unnath/Projects/vivado_and_vitis/final_nn_fpga_tanh/final_nn_fpga_tanh/hls/impl/verilog/project.gen/sources_1/bd/bd_0/ip/bd_0_hls_inst_0/hdl/ip/nn_fpga_top_fcmp_32ns_32ns_1_2_no_dsp_1_ip/nn_fpga_top_fcmp_32ns_32ns_1_2_no_dsp_1_ip.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==nn_fpga_top_fcmp_32ns_32ns_1_2_no_dsp_1_ip || ORIG_REF_NAME==nn_fpga_top_fcmp_32ns_32ns_1_2_no_dsp_1_ip} -quiet] -quiet

# IP: /home/unnath/Projects/vivado_and_vitis/final_nn_fpga_tanh/final_nn_fpga_tanh/hls/impl/verilog/project.gen/sources_1/bd/bd_0/ip/bd_0_hls_inst_0/hdl/ip/nn_fpga_top_fdiv_32ns_32ns_32_16_no_dsp_1_ip/nn_fpga_top_fdiv_32ns_32ns_32_16_no_dsp_1_ip.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==nn_fpga_top_fdiv_32ns_32ns_32_16_no_dsp_1_ip || ORIG_REF_NAME==nn_fpga_top_fdiv_32ns_32ns_32_16_no_dsp_1_ip} -quiet] -quiet

# IP: /home/unnath/Projects/vivado_and_vitis/final_nn_fpga_tanh/final_nn_fpga_tanh/hls/impl/verilog/project.gen/sources_1/bd/bd_0/ip/bd_0_hls_inst_0/hdl/ip/nn_fpga_top_fmul_32ns_32ns_32_4_max_dsp_1_ip/nn_fpga_top_fmul_32ns_32ns_32_4_max_dsp_1_ip.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==nn_fpga_top_fmul_32ns_32ns_32_4_max_dsp_1_ip || ORIG_REF_NAME==nn_fpga_top_fmul_32ns_32ns_32_4_max_dsp_1_ip} -quiet] -quiet

# IP: /home/unnath/Projects/vivado_and_vitis/final_nn_fpga_tanh/final_nn_fpga_tanh/hls/impl/verilog/project.gen/sources_1/bd/bd_0/ip/bd_0_hls_inst_0/hdl/ip/nn_fpga_top_fpext_32ns_64_2_no_dsp_1_ip/nn_fpga_top_fpext_32ns_64_2_no_dsp_1_ip.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==nn_fpga_top_fpext_32ns_64_2_no_dsp_1_ip || ORIG_REF_NAME==nn_fpga_top_fpext_32ns_64_2_no_dsp_1_ip} -quiet] -quiet

# IP: /home/unnath/Projects/vivado_and_vitis/final_nn_fpga_tanh/final_nn_fpga_tanh/hls/impl/verilog/project.gen/sources_1/bd/bd_0/ip/bd_0_hls_inst_0/hdl/ip/nn_fpga_top_fptrunc_64ns_32_2_no_dsp_1_ip/nn_fpga_top_fptrunc_64ns_32_2_no_dsp_1_ip.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==nn_fpga_top_fptrunc_64ns_32_2_no_dsp_1_ip || ORIG_REF_NAME==nn_fpga_top_fptrunc_64ns_32_2_no_dsp_1_ip} -quiet] -quiet

# XDC: /home/unnath/Projects/vivado_and_vitis/final_nn_fpga_tanh/final_nn_fpga_tanh/hls/impl/verilog/project.gen/sources_1/bd/bd_0/ip/bd_0_hls_inst_0/constraints/nn_fpga_top_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_0_hls_inst_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/unnath/Projects/vivado_and_vitis/final_nn_fpga_tanh/final_nn_fpga_tanh/hls/impl/verilog/project.srcs/sources_1/bd/bd_0/ip/bd_0_hls_inst_0/bd_0_hls_inst_0.xci
# IP: The module: 'bd_0_hls_inst_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/unnath/Projects/vivado_and_vitis/final_nn_fpga_tanh/final_nn_fpga_tanh/hls/impl/verilog/project.gen/sources_1/bd/bd_0/ip/bd_0_hls_inst_0/hdl/ip/nn_fpga_top_dadd_64ns_64ns_64_8_full_dsp_1_ip/nn_fpga_top_dadd_64ns_64ns_64_8_full_dsp_1_ip.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==nn_fpga_top_dadd_64ns_64ns_64_8_full_dsp_1_ip || ORIG_REF_NAME==nn_fpga_top_dadd_64ns_64ns_64_8_full_dsp_1_ip} -quiet] -quiet

# IP: /home/unnath/Projects/vivado_and_vitis/final_nn_fpga_tanh/final_nn_fpga_tanh/hls/impl/verilog/project.gen/sources_1/bd/bd_0/ip/bd_0_hls_inst_0/hdl/ip/nn_fpga_top_dcmp_64ns_64ns_1_2_no_dsp_1_ip/nn_fpga_top_dcmp_64ns_64ns_1_2_no_dsp_1_ip.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==nn_fpga_top_dcmp_64ns_64ns_1_2_no_dsp_1_ip || ORIG_REF_NAME==nn_fpga_top_dcmp_64ns_64ns_1_2_no_dsp_1_ip} -quiet] -quiet

# IP: /home/unnath/Projects/vivado_and_vitis/final_nn_fpga_tanh/final_nn_fpga_tanh/hls/impl/verilog/project.gen/sources_1/bd/bd_0/ip/bd_0_hls_inst_0/hdl/ip/nn_fpga_top_faddfsub_32ns_32ns_32_7_full_dsp_1_ip/nn_fpga_top_faddfsub_32ns_32ns_32_7_full_dsp_1_ip.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==nn_fpga_top_faddfsub_32ns_32ns_32_7_full_dsp_1_ip || ORIG_REF_NAME==nn_fpga_top_faddfsub_32ns_32ns_32_7_full_dsp_1_ip} -quiet] -quiet

# IP: /home/unnath/Projects/vivado_and_vitis/final_nn_fpga_tanh/final_nn_fpga_tanh/hls/impl/verilog/project.gen/sources_1/bd/bd_0/ip/bd_0_hls_inst_0/hdl/ip/nn_fpga_top_fcmp_32ns_32ns_1_2_no_dsp_1_ip/nn_fpga_top_fcmp_32ns_32ns_1_2_no_dsp_1_ip.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==nn_fpga_top_fcmp_32ns_32ns_1_2_no_dsp_1_ip || ORIG_REF_NAME==nn_fpga_top_fcmp_32ns_32ns_1_2_no_dsp_1_ip} -quiet] -quiet

# IP: /home/unnath/Projects/vivado_and_vitis/final_nn_fpga_tanh/final_nn_fpga_tanh/hls/impl/verilog/project.gen/sources_1/bd/bd_0/ip/bd_0_hls_inst_0/hdl/ip/nn_fpga_top_fdiv_32ns_32ns_32_16_no_dsp_1_ip/nn_fpga_top_fdiv_32ns_32ns_32_16_no_dsp_1_ip.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==nn_fpga_top_fdiv_32ns_32ns_32_16_no_dsp_1_ip || ORIG_REF_NAME==nn_fpga_top_fdiv_32ns_32ns_32_16_no_dsp_1_ip} -quiet] -quiet

# IP: /home/unnath/Projects/vivado_and_vitis/final_nn_fpga_tanh/final_nn_fpga_tanh/hls/impl/verilog/project.gen/sources_1/bd/bd_0/ip/bd_0_hls_inst_0/hdl/ip/nn_fpga_top_fmul_32ns_32ns_32_4_max_dsp_1_ip/nn_fpga_top_fmul_32ns_32ns_32_4_max_dsp_1_ip.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==nn_fpga_top_fmul_32ns_32ns_32_4_max_dsp_1_ip || ORIG_REF_NAME==nn_fpga_top_fmul_32ns_32ns_32_4_max_dsp_1_ip} -quiet] -quiet

# IP: /home/unnath/Projects/vivado_and_vitis/final_nn_fpga_tanh/final_nn_fpga_tanh/hls/impl/verilog/project.gen/sources_1/bd/bd_0/ip/bd_0_hls_inst_0/hdl/ip/nn_fpga_top_fpext_32ns_64_2_no_dsp_1_ip/nn_fpga_top_fpext_32ns_64_2_no_dsp_1_ip.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==nn_fpga_top_fpext_32ns_64_2_no_dsp_1_ip || ORIG_REF_NAME==nn_fpga_top_fpext_32ns_64_2_no_dsp_1_ip} -quiet] -quiet

# IP: /home/unnath/Projects/vivado_and_vitis/final_nn_fpga_tanh/final_nn_fpga_tanh/hls/impl/verilog/project.gen/sources_1/bd/bd_0/ip/bd_0_hls_inst_0/hdl/ip/nn_fpga_top_fptrunc_64ns_32_2_no_dsp_1_ip/nn_fpga_top_fptrunc_64ns_32_2_no_dsp_1_ip.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==nn_fpga_top_fptrunc_64ns_32_2_no_dsp_1_ip || ORIG_REF_NAME==nn_fpga_top_fptrunc_64ns_32_2_no_dsp_1_ip} -quiet] -quiet

# XDC: /home/unnath/Projects/vivado_and_vitis/final_nn_fpga_tanh/final_nn_fpga_tanh/hls/impl/verilog/project.gen/sources_1/bd/bd_0/ip/bd_0_hls_inst_0/constraints/nn_fpga_top_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_0_hls_inst_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
