// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module nn_fpga_top_nn_fpga_top_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_47_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        h1_address0,
        h1_ce0,
        h1_q0,
        output_r_address0,
        output_r_ce0,
        output_r_we0,
        output_r_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [5:0] h1_address0;
output   h1_ce0;
input  [15:0] h1_q0;
output  [3:0] output_r_address0;
output   output_r_ce0;
output   output_r_we0;
output  [15:0] output_r_d0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln45_fu_150_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [9:0] W2_address0;
wire  signed [8:0] W2_q0;
wire   [3:0] B2_address0;
wire   [6:0] B2_q0;
wire    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln47_fu_179_p2;
reg   [0:0] icmp_ln47_reg_345;
reg   [0:0] icmp_ln47_reg_345_pp0_iter2_reg;
reg   [0:0] icmp_ln47_reg_345_pp0_iter3_reg;
reg   [0:0] icmp_ln47_reg_345_pp0_iter4_reg;
wire   [6:0] select_ln45_fu_185_p3;
reg   [6:0] select_ln45_reg_350;
wire   [3:0] select_ln45_1_fu_193_p3;
reg   [3:0] select_ln45_1_reg_356;
reg   [3:0] select_ln45_1_reg_356_pp0_iter2_reg;
reg   [3:0] select_ln45_1_reg_356_pp0_iter3_reg;
reg   [3:0] select_ln45_1_reg_356_pp0_iter4_reg;
wire   [0:0] icmp_ln47_1_fu_207_p2;
reg   [0:0] icmp_ln47_1_reg_362;
reg   [0:0] icmp_ln47_1_reg_362_pp0_iter2_reg;
reg   [0:0] icmp_ln47_1_reg_362_pp0_iter3_reg;
reg   [0:0] icmp_ln47_1_reg_362_pp0_iter4_reg;
reg   [0:0] icmp_ln47_1_reg_362_pp0_iter5_reg;
reg   [3:0] output_addr_reg_396;
wire   [63:0] zext_ln49_1_fu_243_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln47_fu_230_p1;
wire   [63:0] zext_ln45_fu_259_p1;
reg   [15:0] acc_fu_60;
wire   [15:0] acc_1_fu_279_p4;
reg   [15:0] ap_sig_allocacmp_acc_load;
wire    ap_loop_init;
reg   [6:0] j_fu_64;
wire   [6:0] add_ln47_fu_201_p2;
reg   [3:0] i_2_fu_68;
reg   [9:0] indvar_flatten_fu_72;
wire   [9:0] add_ln45_1_fu_156_p2;
reg   [9:0] ap_sig_allocacmp_indvar_flatten_load;
reg    h1_ce0_local;
reg    W2_ce0_local;
reg    B2_ce0_local;
reg    output_r_we0_local;
wire   [15:0] acc_2_fu_292_p2;
reg    output_r_ce0_local;
wire   [3:0] add_ln45_fu_173_p2;
wire   [9:0] tmp_fu_223_p3;
wire   [9:0] zext_ln49_fu_234_p1;
wire   [9:0] add_ln49_1_fu_237_p2;
wire   [15:0] select_ln45_2_fu_264_p3;
wire  signed [23:0] acc_1_fu_279_p1;
wire   [23:0] grp_fu_304_p3;
wire  signed [15:0] sext_ln51_fu_288_p1;
wire   [23:0] grp_fu_304_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 acc_fu_60 = 16'd0;
#0 j_fu_64 = 7'd0;
#0 i_2_fu_68 = 4'd0;
#0 indvar_flatten_fu_72 = 10'd0;
#0 ap_done_reg = 1'b0;
end

nn_fpga_top_nn_fpga_top_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_47_2_W2_ROM_AUTO_1R #(
    .DataWidth( 9 ),
    .AddressRange( 640 ),
    .AddressWidth( 10 ))
W2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(W2_address0),
    .ce0(W2_ce0_local),
    .q0(W2_q0)
);

nn_fpga_top_nn_fpga_top_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_47_2_B2_ROM_AUTO_1R #(
    .DataWidth( 7 ),
    .AddressRange( 10 ),
    .AddressWidth( 4 ))
B2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(B2_address0),
    .ce0(B2_ce0_local),
    .q0(B2_q0)
);

nn_fpga_top_mac_muladd_16s_9s_24ns_24_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
mac_muladd_16s_9s_24ns_24_4_1_U47(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(h1_q0),
    .din1(W2_q0),
    .din2(grp_fu_304_p2),
    .ce(1'b1),
    .dout(grp_fu_304_p3)
);

nn_fpga_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter5_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            acc_fu_60 <= 16'd0;
        end else if ((ap_enable_reg_pp0_iter6 == 1'b1)) begin
            acc_fu_60 <= {{acc_1_fu_279_p1[23:8]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            i_2_fu_68 <= 4'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            i_2_fu_68 <= select_ln45_1_fu_193_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln45_fu_150_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten_fu_72 <= add_ln45_1_fu_156_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_72 <= 10'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            j_fu_64 <= 7'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            j_fu_64 <= add_ln47_fu_201_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln47_1_reg_362 <= icmp_ln47_1_fu_207_p2;
        icmp_ln47_reg_345 <= icmp_ln47_fu_179_p2;
        select_ln45_1_reg_356 <= select_ln45_1_fu_193_p3;
        select_ln45_reg_350 <= select_ln45_fu_185_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        icmp_ln47_1_reg_362_pp0_iter2_reg <= icmp_ln47_1_reg_362;
        icmp_ln47_1_reg_362_pp0_iter3_reg <= icmp_ln47_1_reg_362_pp0_iter2_reg;
        icmp_ln47_1_reg_362_pp0_iter4_reg <= icmp_ln47_1_reg_362_pp0_iter3_reg;
        icmp_ln47_1_reg_362_pp0_iter5_reg <= icmp_ln47_1_reg_362_pp0_iter4_reg;
        icmp_ln47_reg_345_pp0_iter2_reg <= icmp_ln47_reg_345;
        icmp_ln47_reg_345_pp0_iter3_reg <= icmp_ln47_reg_345_pp0_iter2_reg;
        icmp_ln47_reg_345_pp0_iter4_reg <= icmp_ln47_reg_345_pp0_iter3_reg;
        output_addr_reg_396 <= zext_ln45_fu_259_p1;
        select_ln45_1_reg_356_pp0_iter2_reg <= select_ln45_1_reg_356;
        select_ln45_1_reg_356_pp0_iter3_reg <= select_ln45_1_reg_356_pp0_iter2_reg;
        select_ln45_1_reg_356_pp0_iter4_reg <= select_ln45_1_reg_356_pp0_iter3_reg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        B2_ce0_local = 1'b1;
    end else begin
        B2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        W2_ce0_local = 1'b1;
    end else begin
        W2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln45_fu_150_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter5_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        ap_sig_allocacmp_acc_load = {{acc_1_fu_279_p1[23:8]}};
    end else begin
        ap_sig_allocacmp_acc_load = acc_fu_60;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten_load = 10'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_72;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        h1_ce0_local = 1'b1;
    end else begin
        h1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        output_r_ce0_local = 1'b1;
    end else begin
        output_r_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1) & (icmp_ln47_1_reg_362_pp0_iter5_reg == 1'd1))) begin
        output_r_we0_local = 1'b1;
    end else begin
        output_r_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign B2_address0 = zext_ln45_fu_259_p1;

assign W2_address0 = zext_ln49_1_fu_243_p1;

assign acc_1_fu_279_p1 = grp_fu_304_p3;

assign acc_1_fu_279_p4 = {{acc_1_fu_279_p1[23:8]}};

assign acc_2_fu_292_p2 = ($signed(sext_ln51_fu_288_p1) + $signed(acc_1_fu_279_p4));

assign add_ln45_1_fu_156_p2 = (ap_sig_allocacmp_indvar_flatten_load + 10'd1);

assign add_ln45_fu_173_p2 = (i_2_fu_68 + 4'd1);

assign add_ln47_fu_201_p2 = (select_ln45_fu_185_p3 + 7'd1);

assign add_ln49_1_fu_237_p2 = (tmp_fu_223_p3 + zext_ln49_fu_234_p1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign grp_fu_304_p2 = {{select_ln45_2_fu_264_p3}, {8'd0}};

assign h1_address0 = zext_ln47_fu_230_p1;

assign h1_ce0 = h1_ce0_local;

assign icmp_ln45_fu_150_p2 = ((ap_sig_allocacmp_indvar_flatten_load == 10'd640) ? 1'b1 : 1'b0);

assign icmp_ln47_1_fu_207_p2 = ((add_ln47_fu_201_p2 == 7'd64) ? 1'b1 : 1'b0);

assign icmp_ln47_fu_179_p2 = ((j_fu_64 == 7'd64) ? 1'b1 : 1'b0);

assign output_r_address0 = output_addr_reg_396;

assign output_r_ce0 = output_r_ce0_local;

assign output_r_d0 = acc_2_fu_292_p2;

assign output_r_we0 = output_r_we0_local;

assign select_ln45_1_fu_193_p3 = ((icmp_ln47_fu_179_p2[0:0] == 1'b1) ? add_ln45_fu_173_p2 : i_2_fu_68);

assign select_ln45_2_fu_264_p3 = ((icmp_ln47_reg_345_pp0_iter4_reg[0:0] == 1'b1) ? 16'd0 : ap_sig_allocacmp_acc_load);

assign select_ln45_fu_185_p3 = ((icmp_ln47_fu_179_p2[0:0] == 1'b1) ? 7'd0 : j_fu_64);

assign sext_ln51_fu_288_p1 = $signed(B2_q0);

assign tmp_fu_223_p3 = {{select_ln45_1_reg_356}, {6'd0}};

assign zext_ln45_fu_259_p1 = select_ln45_1_reg_356_pp0_iter4_reg;

assign zext_ln47_fu_230_p1 = select_ln45_reg_350;

assign zext_ln49_1_fu_243_p1 = add_ln49_1_fu_237_p2;

assign zext_ln49_fu_234_p1 = select_ln45_reg_350;

endmodule //nn_fpga_top_nn_fpga_top_Pipeline_VITIS_LOOP_45_1_VITIS_LOOP_47_2
