// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module nn_fpga_top_my_tanh (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        x,
        ap_return
);

parameter    ap_ST_fsm_state1 = 16'd1;
parameter    ap_ST_fsm_state2 = 16'd2;
parameter    ap_ST_fsm_state3 = 16'd4;
parameter    ap_ST_fsm_state4 = 16'd8;
parameter    ap_ST_fsm_state5 = 16'd16;
parameter    ap_ST_fsm_state6 = 16'd32;
parameter    ap_ST_fsm_state7 = 16'd64;
parameter    ap_ST_fsm_state8 = 16'd128;
parameter    ap_ST_fsm_state9 = 16'd256;
parameter    ap_ST_fsm_state10 = 16'd512;
parameter    ap_ST_fsm_state11 = 16'd1024;
parameter    ap_ST_fsm_state12 = 16'd2048;
parameter    ap_ST_fsm_state13 = 16'd4096;
parameter    ap_ST_fsm_state14 = 16'd8192;
parameter    ap_ST_fsm_state15 = 16'd16384;
parameter    ap_ST_fsm_state16 = 16'd32768;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [15:0] x;
output  [15:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[15:0] ap_return;

(* fsm_encoding = "none" *) reg   [15:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [0:0] icmp_ln16_fu_173_p2;
reg   [0:0] icmp_ln16_reg_565;
wire   [0:0] tmp_fu_179_p3;
reg   [0:0] tmp_reg_569;
wire   [15:0] select_ln16_fu_193_p3;
reg   [15:0] select_ln16_reg_575;
wire   [4:0] zext_ln16_fu_212_p1;
reg   [4:0] zext_ln16_reg_582;
wire    ap_CS_fsm_state2;
wire   [4:0] sub_ln16_2_fu_216_p2;
reg   [4:0] sub_ln16_2_reg_587;
wire   [5:0] sub_ln16_3_fu_226_p2;
reg   [5:0] sub_ln16_3_reg_592;
wire  signed [4:0] sub_ln16_1_fu_232_p2;
reg  signed [4:0] sub_ln16_1_reg_597;
wire    ap_CS_fsm_state3;
wire   [63:0] LD_fu_296_p5;
reg   [63:0] LD_reg_602;
wire   [63:0] bitcast_ln767_fu_308_p1;
reg   [63:0] bitcast_ln767_reg_607;
wire    ap_CS_fsm_state4;
wire   [39:0] zext_ln16_4_fu_312_p1;
reg   [39:0] zext_ln16_4_reg_612;
wire    ap_CS_fsm_state5;
wire   [0:0] grp_fu_167_p2;
reg   [0:0] tmp_9_reg_617;
reg   [0:0] tmp_s_reg_621;
wire    ap_CS_fsm_state6;
wire   [4:0] sub_ln22_fu_315_p2;
reg   [4:0] sub_ln22_reg_625;
wire   [31:0] LD_1_fu_386_p1;
reg   [31:0] LD_1_reg_630;
wire    ap_CS_fsm_state7;
wire   [31:0] bitcast_ln777_fu_390_p1;
wire    ap_CS_fsm_state8;
wire   [31:0] grp_generic_tanh_float_s_fu_151_ap_return;
wire    ap_CS_fsm_state10;
wire   [62:0] trunc_ln22_fu_397_p1;
reg   [62:0] trunc_ln22_reg_645;
wire    ap_CS_fsm_state11;
reg   [0:0] tmp_8_reg_650;
reg   [10:0] tmp_7_reg_656;
wire   [51:0] trunc_ln22_1_fu_417_p1;
reg   [51:0] trunc_ln22_1_reg_661;
wire   [53:0] select_ln22_1_fu_441_p3;
reg   [53:0] select_ln22_1_reg_666;
wire    ap_CS_fsm_state12;
wire   [0:0] icmp_ln22_fu_448_p2;
reg   [0:0] icmp_ln22_reg_673;
wire   [0:0] icmp_ln22_1_fu_463_p2;
reg   [0:0] icmp_ln22_1_reg_677;
wire   [10:0] select_ln22_2_fu_481_p3;
reg   [10:0] select_ln22_2_reg_681;
wire   [0:0] icmp_ln22_2_fu_489_p2;
reg   [0:0] icmp_ln22_2_reg_689;
wire   [15:0] select_ln22_4_fu_522_p3;
wire    ap_CS_fsm_state13;
wire   [15:0] select_ln22_3_fu_554_p3;
reg   [15:0] select_ln22_3_reg_698;
wire    ap_CS_fsm_state14;
wire   [15:0] trunc_ln22_3_fu_562_p1;
wire    ap_CS_fsm_state16;
wire    grp_generic_tanh_float_s_fu_151_ap_start;
wire    grp_generic_tanh_float_s_fu_151_ap_done;
wire    grp_generic_tanh_float_s_fu_151_ap_idle;
wire    grp_generic_tanh_float_s_fu_151_ap_ready;
reg   [31:0] x_assign_reg_116;
reg   [15:0] ap_phi_mux_agg_result_0_phi_fu_134_p12;
reg   [15:0] agg_result_0_reg_128;
wire    ap_CS_fsm_state15;
reg    grp_generic_tanh_float_s_fu_151_ap_start_reg;
wire    ap_CS_fsm_state9;
reg   [63:0] grp_fu_167_p0;
reg   [63:0] grp_fu_167_p1;
wire   [15:0] sub_ln16_fu_187_p2;
wire   [15:0] tmp_1_fu_201_p3;
wire   [3:0] trunc_ln16_fu_208_p1;
wire   [5:0] zext_ln16_3_fu_222_p1;
wire   [63:0] zext_ln16_1_fu_237_p1;
wire   [63:0] zext_ln16_2_fu_240_p1;
wire   [63:0] shl_ln16_fu_243_p2;
wire   [62:0] lshr_ln_fu_249_p4;
wire   [0:0] tmp_4_fu_263_p3;
wire   [10:0] select_ln16_1_fu_271_p3;
wire  signed [10:0] sext_ln16_fu_279_p1;
wire   [10:0] add_ln16_fu_283_p2;
wire   [63:0] zext_ln16_5_fu_259_p1;
wire   [11:0] tmp_2_fu_289_p3;
wire   [39:0] zext_ln22_fu_320_p1;
wire   [39:0] shl_ln22_fu_323_p2;
wire   [38:0] lshr_ln1_fu_328_p4;
wire   [0:0] tmp_6_fu_342_p3;
wire   [7:0] select_ln22_fu_350_p3;
wire  signed [7:0] sext_ln22_fu_358_p1;
wire   [7:0] add_ln22_fu_361_p2;
wire   [63:0] zext_ln22_2_fu_338_p1;
wire   [8:0] tmp_3_fu_367_p3;
wire   [63:0] pi_assign_fu_374_p5;
wire   [63:0] grp_fu_163_p1;
wire   [63:0] bitcast_ln735_fu_393_p1;
wire   [52:0] zext_ln22_4_cast_fu_424_p3;
wire   [53:0] zext_ln22_4_fu_431_p1;
wire   [53:0] sub_ln22_1_fu_435_p2;
wire   [11:0] zext_ln22_1_fu_421_p1;
wire   [11:0] sub_ln22_2_fu_453_p2;
wire   [10:0] trunc_ln22_2_fu_459_p1;
wire   [10:0] add_ln22_1_fu_469_p2;
wire   [10:0] sub_ln22_3_fu_475_p2;
wire   [6:0] tmp_10_fu_498_p4;
wire   [15:0] trunc_ln22_5_fu_495_p1;
wire   [15:0] select_ln22_2cast_fu_513_p1;
wire   [0:0] icmp_ln22_4_fu_507_p2;
wire   [15:0] shl_ln22_1_fu_516_p2;
wire   [53:0] zext_ln22_3_fu_542_p1;
wire   [53:0] ashr_ln22_fu_545_p2;
wire   [0:0] icmp_ln22_3_fu_530_p2;
wire   [15:0] trunc_ln22_4_fu_550_p1;
wire   [15:0] select_ln22_5_fu_535_p3;
reg    grp_fu_163_ce;
reg   [4:0] grp_fu_167_opcode;
reg   [15:0] ap_return_preg;
reg   [15:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
reg    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire   [15:0] tmp_1_fu_201_p0;
wire   [0:0] tmp_1_fu_201_p2;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 16'd1;
#0 grp_generic_tanh_float_s_fu_151_ap_start_reg = 1'b0;
#0 ap_return_preg = 16'd0;
end

nn_fpga_top_generic_tanh_float_s grp_generic_tanh_float_s_fu_151(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_generic_tanh_float_s_fu_151_ap_start),
    .ap_done(grp_generic_tanh_float_s_fu_151_ap_done),
    .ap_idle(grp_generic_tanh_float_s_fu_151_ap_idle),
    .ap_ready(grp_generic_tanh_float_s_fu_151_ap_ready),
    .t_in(x_assign_reg_116),
    .ap_return(grp_generic_tanh_float_s_fu_151_ap_return)
);

nn_fpga_top_fpext_32ns_64_2_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
fpext_32ns_64_2_no_dsp_1_U41(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_generic_tanh_float_s_fu_151_ap_return),
    .ce(grp_fu_163_ce),
    .dout(grp_fu_163_p1)
);

nn_fpga_top_dcmp_64ns_64ns_1_2_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 1 ))
dcmp_64ns_64ns_1_2_no_dsp_1_U42(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_167_p0),
    .din1(grp_fu_167_p1),
    .ce(1'b1),
    .opcode(grp_fu_167_opcode),
    .dout(grp_fu_167_p2)
);

nn_fpga_top_ctlz_16_16_1_1 #(
    .din_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
ctlz_16_16_1_1_U43(
    .din(select_ln16_reg_575),
    .dout(tmp_1_fu_201_p3)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_preg <= 16'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state15)) begin
            ap_return_preg <= ap_phi_mux_agg_result_0_phi_fu_134_p12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_generic_tanh_float_s_fu_151_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state9)) begin
            grp_generic_tanh_float_s_fu_151_ap_start_reg <= 1'b1;
        end else if ((grp_generic_tanh_float_s_fu_151_ap_ready == 1'b1)) begin
            grp_generic_tanh_float_s_fu_151_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state12) & (icmp_ln22_fu_448_p2 == 1'd1))) begin
        agg_result_0_reg_128 <= 16'd0;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        agg_result_0_reg_128 <= select_ln22_4_fu_522_p3;
    end else if (((1'b1 == ap_CS_fsm_state15) & (((icmp_ln16_reg_565 == 1'd1) & (icmp_ln22_2_reg_689 == 1'd0) & (icmp_ln22_1_reg_677 == 1'd1) & (icmp_ln22_reg_673 == 1'd0)) | ((tmp_s_reg_621 == 1'd0) & (tmp_9_reg_617 == 1'd0) & (icmp_ln22_2_reg_689 == 1'd0) & (icmp_ln22_1_reg_677 == 1'd1) & (icmp_ln22_reg_673 == 1'd0))))) begin
        agg_result_0_reg_128 <= select_ln22_3_reg_698;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        agg_result_0_reg_128 <= trunc_ln22_3_fu_562_p1;
    end else if (((grp_fu_167_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state6))) begin
        agg_result_0_reg_128 <= 16'd65280;
    end else if (((grp_fu_167_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
        agg_result_0_reg_128 <= 16'd256;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln16_fu_173_p2 == 1'd1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        x_assign_reg_116 <= 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        x_assign_reg_116 <= bitcast_ln777_fu_390_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        LD_1_reg_630 <= LD_1_fu_386_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        LD_reg_602 <= LD_fu_296_p5;
        sub_ln16_1_reg_597 <= sub_ln16_1_fu_232_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        bitcast_ln767_reg_607 <= bitcast_ln767_fu_308_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        icmp_ln16_reg_565 <= icmp_ln16_fu_173_p2;
        select_ln16_reg_575 <= select_ln16_fu_193_p3;
        tmp_reg_569 <= x[32'd15];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        icmp_ln22_1_reg_677 <= icmp_ln22_1_fu_463_p2;
        icmp_ln22_2_reg_689 <= icmp_ln22_2_fu_489_p2;
        icmp_ln22_reg_673 <= icmp_ln22_fu_448_p2;
        select_ln22_1_reg_666 <= select_ln22_1_fu_441_p3;
        select_ln22_2_reg_681 <= select_ln22_2_fu_481_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        select_ln22_3_reg_698 <= select_ln22_3_fu_554_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        sub_ln16_2_reg_587 <= sub_ln16_2_fu_216_p2;
        sub_ln16_3_reg_592 <= sub_ln16_3_fu_226_p2;
        zext_ln16_reg_582[3 : 0] <= zext_ln16_fu_212_p1[3 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        sub_ln22_reg_625 <= sub_ln22_fu_315_p2;
        tmp_s_reg_621 <= grp_fu_167_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        tmp_7_reg_656 <= {{bitcast_ln735_fu_393_p1[62:52]}};
        tmp_8_reg_650 <= bitcast_ln735_fu_393_p1[32'd63];
        trunc_ln22_1_reg_661 <= trunc_ln22_1_fu_417_p1;
        trunc_ln22_reg_645 <= trunc_ln22_fu_397_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        tmp_9_reg_617 <= grp_fu_167_p2;
        zext_ln16_4_reg_612[15 : 0] <= zext_ln16_4_fu_312_p1[15 : 0];
    end
end

always @ (*) begin
    if ((grp_generic_tanh_float_s_fu_151_ap_done == 1'b0)) begin
        ap_ST_fsm_state10_blk = 1'b1;
    end else begin
        ap_ST_fsm_state10_blk = 1'b0;
    end
end

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state15) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state15) & (((icmp_ln16_reg_565 == 1'd1) & (icmp_ln22_2_reg_689 == 1'd0) & (icmp_ln22_1_reg_677 == 1'd1) & (icmp_ln22_reg_673 == 1'd0)) | ((tmp_s_reg_621 == 1'd0) & (tmp_9_reg_617 == 1'd0) & (icmp_ln22_2_reg_689 == 1'd0) & (icmp_ln22_1_reg_677 == 1'd1) & (icmp_ln22_reg_673 == 1'd0))))) begin
        ap_phi_mux_agg_result_0_phi_fu_134_p12 = select_ln22_3_reg_698;
    end else begin
        ap_phi_mux_agg_result_0_phi_fu_134_p12 = agg_result_0_reg_128;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        ap_return = ap_phi_mux_agg_result_0_phi_fu_134_p12;
    end else begin
        ap_return = ap_return_preg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | ((1'b1 == ap_CS_fsm_state10) & (grp_generic_tanh_float_s_fu_151_ap_done == 1'b1)))) begin
        grp_fu_163_ce = 1'b1;
    end else begin
        grp_fu_163_ce = 1'b0;
    end
end

always @ (*) begin
    if (((grp_fu_167_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        grp_fu_167_opcode = 5'd4;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_167_opcode = 5'd2;
    end else begin
        grp_fu_167_opcode = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_167_p0 = bitcast_ln767_reg_607;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_167_p0 = bitcast_ln767_fu_308_p1;
    end else begin
        grp_fu_167_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_167_p1 = 64'd13832806255468478464;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_167_p1 = 64'd4609434218613702656;
    end else begin
        grp_fu_167_p1 = 'bx;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((icmp_ln16_fu_173_p2 == 1'd1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else if (((icmp_ln16_fu_173_p2 == 1'd0) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((grp_fu_167_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state6 : begin
            if (((grp_fu_167_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            if (((1'b1 == ap_CS_fsm_state10) & (grp_generic_tanh_float_s_fu_151_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            if (((1'b1 == ap_CS_fsm_state12) & (icmp_ln22_2_fu_489_p2 == 1'd0) & (icmp_ln22_1_fu_463_p2 == 1'd1) & (icmp_ln22_fu_448_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else if (((1'b1 == ap_CS_fsm_state12) & (icmp_ln22_2_fu_489_p2 == 1'd0) & (icmp_ln22_1_fu_463_p2 == 1'd0) & (icmp_ln22_fu_448_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else if (((1'b1 == ap_CS_fsm_state12) & (icmp_ln22_2_fu_489_p2 == 1'd1) & (icmp_ln22_fu_448_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign LD_1_fu_386_p1 = pi_assign_fu_374_p5[31:0];

assign LD_fu_296_p5 = {{tmp_2_fu_289_p3}, {zext_ln16_5_fu_259_p1[51:0]}};

assign add_ln16_fu_283_p2 = ($signed(select_ln16_1_fu_271_p3) + $signed(sext_ln16_fu_279_p1));

assign add_ln22_1_fu_469_p2 = ($signed(trunc_ln22_2_fu_459_p1) + $signed(11'd2040));

assign add_ln22_fu_361_p2 = ($signed(select_ln22_fu_350_p3) + $signed(sext_ln22_fu_358_p1));

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign ashr_ln22_fu_545_p2 = $signed(select_ln22_1_reg_666) >>> zext_ln22_3_fu_542_p1;

assign bitcast_ln735_fu_393_p1 = grp_fu_163_p1;

assign bitcast_ln767_fu_308_p1 = LD_reg_602;

assign bitcast_ln777_fu_390_p1 = LD_1_reg_630;

assign grp_generic_tanh_float_s_fu_151_ap_start = grp_generic_tanh_float_s_fu_151_ap_start_reg;

assign icmp_ln16_fu_173_p2 = ((x == 16'd0) ? 1'b1 : 1'b0);

assign icmp_ln22_1_fu_463_p2 = (($signed(sub_ln22_2_fu_453_p2) > $signed(12'd8)) ? 1'b1 : 1'b0);

assign icmp_ln22_2_fu_489_p2 = ((sub_ln22_2_fu_453_p2 == 12'd8) ? 1'b1 : 1'b0);

assign icmp_ln22_3_fu_530_p2 = ((select_ln22_2_reg_681 < 11'd54) ? 1'b1 : 1'b0);

assign icmp_ln22_4_fu_507_p2 = ((tmp_10_fu_498_p4 == 7'd0) ? 1'b1 : 1'b0);

assign icmp_ln22_fu_448_p2 = ((trunc_ln22_reg_645 == 63'd0) ? 1'b1 : 1'b0);

assign lshr_ln1_fu_328_p4 = {{shl_ln22_fu_323_p2[39:1]}};

assign lshr_ln_fu_249_p4 = {{shl_ln16_fu_243_p2[63:1]}};

assign pi_assign_fu_374_p5 = {{zext_ln22_2_fu_338_p1[63:32]}, {tmp_3_fu_367_p3}, {zext_ln22_2_fu_338_p1[22:0]}};

assign select_ln16_1_fu_271_p3 = ((tmp_4_fu_263_p3[0:0] == 1'b1) ? 11'd1023 : 11'd1022);

assign select_ln16_fu_193_p3 = ((tmp_fu_179_p3[0:0] == 1'b1) ? sub_ln16_fu_187_p2 : x);

assign select_ln22_1_fu_441_p3 = ((tmp_8_reg_650[0:0] == 1'b1) ? sub_ln22_1_fu_435_p2 : zext_ln22_4_fu_431_p1);

assign select_ln22_2_fu_481_p3 = ((icmp_ln22_1_fu_463_p2[0:0] == 1'b1) ? add_ln22_1_fu_469_p2 : sub_ln22_3_fu_475_p2);

assign select_ln22_2cast_fu_513_p1 = select_ln22_2_reg_681;

assign select_ln22_3_fu_554_p3 = ((icmp_ln22_3_fu_530_p2[0:0] == 1'b1) ? trunc_ln22_4_fu_550_p1 : select_ln22_5_fu_535_p3);

assign select_ln22_4_fu_522_p3 = ((icmp_ln22_4_fu_507_p2[0:0] == 1'b1) ? shl_ln22_1_fu_516_p2 : 16'd0);

assign select_ln22_5_fu_535_p3 = ((tmp_8_reg_650[0:0] == 1'b1) ? 16'd65535 : 16'd0);

assign select_ln22_fu_350_p3 = ((tmp_6_fu_342_p3[0:0] == 1'b1) ? 8'd127 : 8'd126);

assign sext_ln16_fu_279_p1 = sub_ln16_1_fu_232_p2;

assign sext_ln22_fu_358_p1 = sub_ln16_1_reg_597;

assign shl_ln16_fu_243_p2 = zext_ln16_1_fu_237_p1 << zext_ln16_2_fu_240_p1;

assign shl_ln22_1_fu_516_p2 = trunc_ln22_5_fu_495_p1 << select_ln22_2cast_fu_513_p1;

assign shl_ln22_fu_323_p2 = zext_ln16_4_reg_612 << zext_ln22_fu_320_p1;

assign sub_ln16_1_fu_232_p2 = (5'd8 - zext_ln16_reg_582);

assign sub_ln16_2_fu_216_p2 = ($signed(5'd16) - $signed(zext_ln16_fu_212_p1));

assign sub_ln16_3_fu_226_p2 = ($signed(6'd54) - $signed(zext_ln16_3_fu_222_p1));

assign sub_ln16_fu_187_p2 = (16'd0 - x);

assign sub_ln22_1_fu_435_p2 = (54'd0 - zext_ln22_4_fu_431_p1);

assign sub_ln22_2_fu_453_p2 = (12'd1075 - zext_ln22_1_fu_421_p1);

assign sub_ln22_3_fu_475_p2 = (11'd8 - trunc_ln22_2_fu_459_p1);

assign sub_ln22_fu_315_p2 = ($signed(5'd25) - $signed(sub_ln16_2_reg_587));

assign tmp_10_fu_498_p4 = {{select_ln22_2_reg_681[10:4]}};

assign tmp_2_fu_289_p3 = {{tmp_reg_569}, {add_ln16_fu_283_p2}};

assign tmp_3_fu_367_p3 = {{tmp_reg_569}, {add_ln22_fu_361_p2}};

assign tmp_4_fu_263_p3 = shl_ln16_fu_243_p2[32'd54];

assign tmp_6_fu_342_p3 = shl_ln22_fu_323_p2[32'd25];

assign tmp_fu_179_p3 = x[32'd15];

assign trunc_ln16_fu_208_p1 = tmp_1_fu_201_p3[3:0];

assign trunc_ln22_1_fu_417_p1 = bitcast_ln735_fu_393_p1[51:0];

assign trunc_ln22_2_fu_459_p1 = sub_ln22_2_fu_453_p2[10:0];

assign trunc_ln22_3_fu_562_p1 = select_ln22_1_reg_666[15:0];

assign trunc_ln22_4_fu_550_p1 = ashr_ln22_fu_545_p2[15:0];

assign trunc_ln22_5_fu_495_p1 = select_ln22_1_reg_666[15:0];

assign trunc_ln22_fu_397_p1 = bitcast_ln735_fu_393_p1[62:0];

assign zext_ln16_1_fu_237_p1 = select_ln16_reg_575;

assign zext_ln16_2_fu_240_p1 = sub_ln16_3_reg_592;

assign zext_ln16_3_fu_222_p1 = sub_ln16_2_fu_216_p2;

assign zext_ln16_4_fu_312_p1 = select_ln16_reg_575;

assign zext_ln16_5_fu_259_p1 = lshr_ln_fu_249_p4;

assign zext_ln16_fu_212_p1 = trunc_ln16_fu_208_p1;

assign zext_ln22_1_fu_421_p1 = tmp_7_reg_656;

assign zext_ln22_2_fu_338_p1 = lshr_ln1_fu_328_p4;

assign zext_ln22_3_fu_542_p1 = select_ln22_2_reg_681;

assign zext_ln22_4_cast_fu_424_p3 = {{1'd1}, {trunc_ln22_1_reg_661}};

assign zext_ln22_4_fu_431_p1 = zext_ln22_4_cast_fu_424_p3;

assign zext_ln22_fu_320_p1 = sub_ln22_reg_625;

always @ (posedge ap_clk) begin
    zext_ln16_reg_582[4] <= 1'b0;
    zext_ln16_4_reg_612[39:16] <= 24'b000000000000000000000000;
end

endmodule //nn_fpga_top_my_tanh
