-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity nn_fpga_top_B1_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 5; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 64
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of nn_fpga_top_B1_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "10110", 1 => "11110", 2 => "11111", 3 => "00110", 
    4 => "00011", 5 => "00101", 6 => "00100", 7 => "01000", 
    8 => "11111", 9 => "10110", 10 => "00010", 11 => "00101", 
    12 => "11001", 13 => "10110", 14 => "00010", 15 => "00111", 
    16 => "11011", 17 => "00001", 18 => "00010", 19 => "00001", 
    20 => "11100", 21 => "00001", 22 => "11101", 23 => "11000", 
    24 => "00000", 25 => "01000", 26 => "00111", 27 => "11001", 
    28 => "01110", 29 => "01000", 30 => "00110", 31 => "11000", 
    32 => "00001", 33 => "01000", 34 => "00100", 35 => "11000", 
    36 => "11000", 37 => "00111", 38 => "00100", 39 => "01011", 
    40 => "10111", 41 => "00110", 42 => "11010", 43 => "11101", 
    44 => "00001", 45 => "01001", 46 => "00000", 47 => "01001", 
    48 => "11110", 49 => "10010", 50 => "11001", 51 => "00000", 
    52 => "00001", 53 => "00101", 54 => "00100", 55 => "00000", 
    56 => "00101", 57 => "01000", 58 => "00010", 59 => "01011", 
    60 => "11011", 61 => "11110", 62 => "01000", 63 => "01011");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

